# TWiki plugin makefile
# Includes "standard rules"
# Variables

# Default path to cloned jbrowse repository
# Edit the following line to reflect your jbrowse root path:
# (Can also override with 'make JROOT=...' on command line)
JROOT = /usr/local/jbrowse

# include standard makefile
include $(JROOT)/mk/standard.mk

# file containing diagnostic info
DIAGNOSTICS = diagnostics.txt


# Public phony targets
# NB 'diagnostics' is NOT a phony target; this ensures it is rebuilt every time 'make' is run
PHONIES = all clean diagnostics-clean
.PHONY: $(PHONIES)

all: jbrowse diagnostics

clean: jbrowse-clean diagnostics-clean


# Private rules
# diagnostics
diagnostics:
	echo DIAGNOSTIC INFORMATION > $(DIAGNOSTICS)
	echo The following files were recognized: >> $(DIAGNOSTICS)
	echo FASTA files: $(ALL_FASTA) >> $(DIAGNOSTICS)
	echo BED files: $(ALL_BED) >> $(DIAGNOSTICS)
	echo GFF files: $(ALL_GFF) >> $(DIAGNOSTICS)
	echo GFF3 files: $(ALL_GFF3) >> $(DIAGNOSTICS)
	echo WIG files: $(ALL_WIG) >> $(DIAGNOSTICS)
	test -e $(CONFIG) && (echo Config files: $(CONFIG) >> $(DIAGNOSTICS)) || eval

diagnostics-clean:
	rm $(DIAGNOSTICS)
