define( [
            'dojo/_base/declare',
            'dojo/dom-construct',
            './Overlay'
        ],
        function( declare, dom, Overlay ) {

return declare( null, {

    constructor: function( args ) {
    },

    show: function( args ) {
        new Overlay(name).addToDisplay(dom.create('div',{innerHTML: this._words()}))
            .addButton('test', function(){alert('You clicked the button!');})
            .show( { title: 'Title section' } );
    },

    _words: function(){
      // returns some random text from hipster ipsum.
     return "Fanny pack try-hard est fugiat sustainable banjo.<br \> Portland jean shorts magna accusamus twee salvia ad, dolor occupy umami mollit.<br \> Excepteur nihil fashion axe, single-origin coffee incididunt fingerstache put a bird on it sed carles tempor id chambray.<br \> Bushwick eu kogi truffaut sustainable.<br \> Velit chillwave locavore, hoodie tumblr butcher salvia cosby sweater reprehenderit accusamus ethnic wes anderson twee nihil laboris.<br \> Anim nihil four loko biodiesel, est banh mi portland helvetica plaid hashtag single-origin coffee tonx american apparel.<br \> Non ugh ennui, duis blue bottle tumblr quinoa gastropub accusamus skateboard +1 tempor vero williamsburg seitan.<br \><br \> \
Banksy vinyl trust fund, american apparel seitan 3 wolf moon meh keffiyeh iphone aliqua cillum non pinterest whatever letterpress.<br \> Letterpress leggings deserunt polaroid, typewriter id DIY duis swag.<br \> Flannel selfies street art, freegan beard blue bottle try-hard elit fap wolf adipisicing wayfarers sriracha exercitation pinterest.<br \> Scenester disrupt carles messenger bag meh mollit.<br \> Ad truffaut next level pour-over delectus.<br \> Yr Austin vero lo-fi pug.<br \> Vinyl godard id umami bespoke, yr single-origin coffee freegan craft beer flannel occaecat dreamcatcher fashion axe.<br \><br \> \
Marfa chillwave pug, do ea tousled occupy polaroid kogi blog cliche.<br \> Cray incididunt locavore skateboard aesthetic messenger bag.<br \> Stumptown selfies in, tattooed echo park wayfarers dolore et YOLO ullamco.<br \> Church-key salvia 8-bit accusamus gluten-free, banksy godard nostrud.<br \> Next level flannel accusamus, sed enim direct trade yr mollit.<br \> Literally kogi meggings locavore voluptate hoodie ennui.<br \> Nesciunt helvetica bushwick echo park master cleanse, enim cillum tousled ad.<br \><br \> \
Adipisicing cliche ea hashtag, leggings food truck freegan non 8-bit nulla squid helvetica lomo chambray messenger bag.<br \> Jean shorts cosby sweater wes anderson, selvage pop-up +1 fanny pack whatever.<br \> Nihil iphone whatever, swag carles twee mumblecore proident pop-up freegan.<br \> Deserunt cosby sweater actually, disrupt banh mi cray umami shoreditch wayfarers single-origin coffee est ad terry richardson selvage food truck.<br \> Keffiyeh bushwick sint, aute plaid cillum food truck.<br \> VHS occupy pitchfork meggings chambray locavore.<br \> Single-origin coffee accusamus mcsweeney's banh mi put a bird on it ex.<br \><br \> \
Nisi forage williamsburg truffaut duis try-hard.<br \> Williamsburg pitchfork pariatur, est try-hard 90's flexitarian.<br \> Gluten-free nulla selfies pitchfork ex.<br \> Kale chips nulla aliquip mlkshk direct trade quis.<br \> Culpa occupy organic, eiusmod YOLO vinyl sriracha odio scenester carles salvia disrupt tumblr echo park laboris.<br \> Tumblr scenester marfa craft beer meh tempor.<br \> Ethnic odio deep v leggings ea.<br \><br \> \
Street art selfies brooklyn, sunt swag messenger bag post-ironic.<br \> Keffiyeh small batch selfies dreamcatcher, tonx keytar chambray.<br \> Officia qui semiotics squid ex.<br \> Aesthetic scenester deserunt vinyl artisan.<br \> Cupidatat et vero, squid thundercats master cleanse ugh pork belly helvetica food truck.<br \> Ullamco laborum carles odd future.<br \> Consectetur laborum eiusmod sint accusamus, tousled disrupt banh mi deserunt assumenda small batch.<br \><br \> \
Seitan wayfarers nostrud, scenester sartorial organic photo booth aute chillwave dolore art party.<br \> Truffaut pitchfork vinyl, semiotics gastropub marfa selfies blue bottle terry richardson PBR quinoa food truck occaecat.<br \> Meh flexitarian qui jean shorts portland.<br \> Truffaut elit cliche authentic kale chips try-hard.<br \> Meggings brunch consequat shoreditch actually fap.<br \> Ea tofu ugh, chillwave cosby sweater velit polaroid sint mumblecore tempor nesciunt incididunt minim.<br \> 3 wolf moon skateboard pour-over banh mi.<br \><br \> \
Non letterpress 3 wolf moon, mollit blue bottle pitchfork eu nihil.<br \> Fixie kale chips terry richardson, tonx single-origin coffee blue bottle tempor fingerstache.<br \> Mollit fugiat mustache cred kale chips.<br \> Accusamus +1 ethnic nostrud, gastropub twee assumenda eu enim swag fashion axe sint est.<br \> Labore odd future tofu forage, squid eu literally esse.<br \> Cred tousled fingerstache direct trade vegan leggings in esse meggings, actually next level.<br \> Raw denim lo-fi 90's quis, chillwave tempor incididunt ut jean shorts occupy meggings YOLO sunt.<br \><br \> \
Lo-fi typewriter disrupt occupy blue bottle etsy.<br \> Assumenda sapiente leggings wolf pinterest craft beer.<br \> Quinoa direct trade mustache, deserunt cliche trust fund fanny pack typewriter sapiente aute.<br \> Exercitation aute sed esse VHS elit.<br \> Sed blue bottle delectus marfa, tumblr dolor nisi.<br \> Nihil nostrud ennui, delectus forage officia vero narwhal fixie.<br \> PBR sustainable cillum, velit carles pickled shoreditch bicycle rights duis wayfarers meggings ugh.<br \><br \> \
Mustache single-origin coffee meh cred, fugiat squid non skateboard banksy id american apparel tumblr photo booth dolore.<br \> 3 wolf moon dolore pork belly adipisicing occaecat, thundercats actually scenester.<br \> Helvetica authentic try-hard pickled, sunt tousled sriracha fixie keytar biodiesel culpa reprehenderit delectus.<br \> +1 truffaut ethnic delectus, chillwave scenester incididunt accusamus.<br \> Anim art party forage, fixie ut fashion axe artisan pork belly tumblr elit occupy brooklyn odio YOLO neutra.<br \> Cray butcher brooklyn, tonx wayfarers thundercats adipisicing scenester iphone aliquip id cred proident vinyl.<br \> Adipisicing banksy mcsweeney's williamsburg.<br \><br \> \
Ethnic dolore deserunt nulla, marfa yr brooklyn.<br \> Fugiat labore swag, brooklyn irony hoodie bushwick disrupt kale chips pug anim pickled vegan.<br \> Marfa farm-to-table authentic, in delectus trust fund seitan labore pop-up cred wolf.<br \> Beard portland biodiesel leggings.<br \> Velit marfa synth, quinoa VHS art party sartorial.<br \> Ennui jean shorts ea church-key, flannel pickled direct trade incididunt 3 wolf moon.<br \> Vinyl tempor excepteur occupy.<br \><br \> \
Brunch before they sold out delectus, fingerstache farm-to-table commodo pinterest vegan.<br \> Ugh cred food truck hoodie proident consectetur.<br \> Hella retro leggings neutra fugiat gluten-free.<br \> Next level pitchfork yr cray minim, incididunt sapiente Austin in officia pickled four loko pinterest terry richardson portland.<br \> Proident laborum ennui scenester pour-over gluten-free, cillum brooklyn flannel nihil.<br \> American apparel lo-fi yr, elit accusamus flexitarian forage trust fund butcher wolf bespoke godard adipisicing.<br \> Sustainable kale chips exercitation incididunt esse.<br \><br \> \
Master cleanse do blog, dreamcatcher wes anderson 8-bit flexitarian odd future flannel dolor viral raw denim anim lo-fi.<br \> Odio cardigan narwhal, vero nihil direct trade art party.<br \> Officia ea gastropub chillwave nisi, cosby sweater actually duis qui tousled farm-to-table voluptate.<br \> Put a bird on it fingerstache enim DIY.<br \> Selvage tonx exercitation banjo master cleanse, cillum tousled wolf odd future in american apparel est sint.<br \> Semiotics brunch flannel kogi.<br \> Marfa beard gluten-free eiusmod portland chillwave.<br \><br \> \
Godard quis consequat helvetica seitan 90's.<br \> Hoodie skateboard four loko master cleanse, reprehenderit eu vinyl squid street art ennui stumptown deserunt est butcher.<br \> Sapiente aliquip squid id dreamcatcher.<br \> Et four loko consectetur semiotics chambray.<br \> Iphone do vinyl, ullamco quis hoodie cardigan shoreditch try-hard fixie hashtag literally artisan qui.<br \> Neutra leggings narwhal, freegan pop-up ethnic iphone esse nisi sunt wes anderson single-origin coffee 90's lomo quis.<br \> Put a bird on it blog irony, wes anderson aesthetic plaid marfa incididunt pickled shoreditch keffiyeh.<br \><br \> \
Iphone odd future qui exercitation, ex pariatur whatever church-key next level mcsweeney's consequat american apparel.<br \> Plaid adipisicing photo booth, 90's 3 wolf moon bicycle rights esse twee biodiesel fingerstache portland keytar.<br \> Hoodie lomo eiusmod, blog vegan before they sold out disrupt wes anderson sartorial salvia excepteur street art food truck Austin tempor.<br \> Veniam ea fingerstache fugiat helvetica, ex echo park scenester brooklyn sartorial ut commodo seitan.<br \> Gluten-free assumenda four loko, ugh enim lo-fi hella seitan vinyl.<br \> Incididunt consectetur sriracha, terry richardson keffiyeh eiusmod fap skateboard occaecat.<br \> 3 wolf moon hoodie jean shorts, portland deserunt semiotics placeat incididunt scenester carles pinterest mollit 8-bit.<br \><br \> \
Labore aesthetic laborum est, intelligentsia selfies lo-fi you probably haven't heard of them messenger bag.<br \> Mollit kogi quis elit readymade.<br \> Banjo aliquip ad +1.<br \> Fixie selvage tattooed four loko.<br \> Small batch quis brunch delectus, synth tumblr proident you probably haven't heard of them direct trade.<br \> Duis swag mumblecore ethical flannel.<br \> Consectetur qui ex enim cillum, occaecat aliquip tempor readymade beard portland banksy wes anderson organic flexitarian.<br \> \
Farm-to-table tumblr irony, odio meh mustache trust fund seitan sint laborum enim.<br \> Pariatur pitchfork truffaut salvia pickled, cardigan four loko direct trade occaecat.<br \> Ex incididunt mixtape, echo park dreamcatcher art party accusamus meh kale chips tofu cillum aesthetic delectus mumblecore nostrud.<br \> Organic VHS selvage carles enim.<br \> Exercitation reprehenderit 90's sartorial, accusamus irure banh mi pug raw denim retro.<br \> Actually scenester velit selfies odd future vegan gluten-free umami, aesthetic voluptate.<br \> Stumptown leggings lomo, synth YOLO high life chillwave meggings ea street art in flannel.<br \>"
}

});
});

