{
    items: [
        {   label: 'George Washington',
            type: 'President',
            presidency: 1,
            index: 1,
            term: [ 1, 2 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Portrait_of_George_Washington.jpeg/100px-Portrait_of_George_Washington.jpeg',
            url: 'http://en.wikipedia.org/wiki/George_Washington',
            party: "No Party",
            birth: '1732-02-22',
            death: '1799-12-14',
            birthPlace: 'Westmoreland County, Virginia, USA',
            deathPlace: 'Mount Vernon, Virginia',
            religion: [ "Anglican", "Episcopal", "Deist" ]
        },
        {   label: 'John Adams',
            type: 'President',
            presidency: 2,
            index: 2,
            term: [ 3 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Johnadamsvp.flipped.jpg/100px-Johnadamsvp.flipped.jpg',
            url: 'http://en.wikipedia.org/wiki/John_Adams',
            party: "Federalist",
            birth: '1735-10-30',
            death: '1826-07-04',
            birthPlace: 'Braintree, Massachusetts, USA',
            deathPlace: 'Quincy, Massachusetts',
            religion: [ "Unitarian" ]
        },
        {   label: 'Thomas Jefferson',
            type: 'President',
            presidency: 3,
            index: 3,
            term: [ 4, 5 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/en/thumb/4/46/T_Jefferson_by_Charles_Willson_Peale_1791_2.jpg/100px-T_Jefferson_by_Charles_Willson_Peale_1791_2.jpg',
            url: 'http://en.wikipedia.org/wiki/Thomas_Jefferson',
            party: "Democratic-Republican",
            birth: '1743-04-13',
            death: '1826-07-04',
            birthPlace: 'Albemarle County, Virginia, USA',
            deathPlace: 'Charlottesville, Virginia',
            religion: [ "Deism", "quasi Unitarianism" ]
        },
        {   label: 'James Madison',
            type: 'President',
            presidency: 4,
            index: 4,
            term: [ 6, 7 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Jm4.gif/100px-Jm4.gif',
            url: 'http://en.wikipedia.org/wiki/James_Madison',
            party: "Democratic-Republican",
            birth: '1751-03-16',
            death: '1836-06-28',
            birthPlace: 'Port Conway, Virginia, USA',
            deathPlace: 'Montpelier, Virginia',
            religion: [ "no affiliation" ]
        },
        {   label: 'James Monroe',
            type: 'President',
            presidency: 5,
            index: 5,
            term: [ 8, 9 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Jamesmonroe-npgallery.jpg/100px-Jamesmonroe-npgallery.jpg',
            url: 'http://en.wikipedia.org/wiki/James_Monroe',
            party: "Democratic-Republican",
            birth: '1758-04-28',
            death: '1831-07-04',
            birthPlace: 'Westmoreland County, Virginia, USA',
            deathPlace: 'New York City, New York',
            religion: [ "no affiliation" ]
        },
        {   label: 'John Quincy Adams',
            type: 'President',
            presidency: 6,
            index: 6,
            term: [ 10 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/64/John_Quincy_Adams.jpg/100px-John_Quincy_Adams.jpg',
            url: 'http://en.wikipedia.org/wiki/John_Quincy_Adams',
            party: "Democratic-Republican",
            birth: '1767-07-11',
            death: '1848-02-23',
            birthPlace: 'Braintree, Massachusetts, USA',
            deathPlace: 'Washington, D.C.',
            religion: [ "Unitarian" ]
        },
        {   label: 'Andrew Jackson',
            type: 'President',
            presidency: 7,
            index: 7,
            term: [ 11, 12 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Andrew_jackson_head.gif/100px-Andrew_jackson_head.gif',
            url: 'http://en.wikipedia.org/wiki/Andrew_Jackson',
            party: "Democratic",
            birth: '1767-03-15',
            death: '1845-06-08',
            birthPlace: 'Waxhaws area, South Carolina, USA',
            deathPlace: 'Nashville, Tennessee',
            religion: [ "Presbyterian" ]
        },
        {   label: 'Martin Van Buren',
            type: 'President',
            presidency: 8,
            index: 8,
            term: [ 13 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Martin_Van_Buren.jpg/100px-Martin_Van_Buren.jpg',
            url: 'http://en.wikipedia.org/wiki/Martin_Van_Buren',
            party: "Democratic",
            birth: '1782-12-05',
            death: '1862-07-24',
            birthPlace: 'Kinderhook, New York, USA',
            deathPlace: 'Kinderhook, New York',
            religion: [ "Dutch Reformed" ]
        },
        {   label: 'William Harrison',
            type: 'President',
            presidency: 9,
            index: 9,
            term: [ 14 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/William_Henry_Harrison.png/100px-William_Henry_Harrison.png',
            url: 'http://en.wikipedia.org/wiki/William_Henry_Harrison',
            party: "Whig",
            birth: '1773-02-09',
            death: '1841-04-04',
            birthPlace: 'Charles City County, Virginia, USA',
            deathPlace: 'Washington, D.C.',
            religion: [ "Episcopal" ]
        },
        {   label: 'John Tyler',
            type: 'President',
            presidency: 10,
            index: 10,
            term: [ 14 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/John_Tyler.jpg/100px-John_Tyler.jpg',
            url: 'http://en.wikipedia.org/wiki/John_Tyler',
            party: "Whig",
            birth: '1790-03-29',
            death: '1862-01-18',
            birthPlace: 'Charles City County, Virginia, USA',
            deathPlace: 'Richmond, Virginia',
            religion: [ "The Episcopal Church", "Deism" ]
        },
        {   label: 'James Polk',
            type: 'President',
            presidency: 11,
            index: 11,
            term: [ 15 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/en/thumb/b/be/Polkpolk.jpg/100px-Polkpolk.jpg',
            url: 'http://en.wikipedia.org/wiki/James_K._Polk',
            party: "Democratic",
            birth: '1795-11-02',
            death: '1849-06-15',
            birthPlace: 'Mecklenburg County, North Carolina, USA',
            deathPlace: 'Nashville, Tennessee',
            religion: [ "Presbyterian", "Methodist" ]
        },
        {   label: 'Zachary Taylor',
            type: 'President',
            presidency: 12,
            index: 12,
            term: [ 16 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Zachary_Taylor.jpg/100px-Zachary_Taylor.jpg',
            url: 'http://en.wikipedia.org/wiki/Zachary_Taylor',
            party: "Whig",
            birth: '1784-11-24',
            death: '1850-07-09',
            birthPlace: 'Barboursville, Virginia, USA',
            deathPlace: 'Washington, D.C.',
            religion: [ "Episcopal" ]
        },
        {   label: 'Millard Fillmore',
            type: 'President',
            presidency: 13,
            index: 13,
            term: [ 16 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Millard_Fillmore.jpg/100px-Millard_Fillmore.jpg',
            url: 'http://en.wikipedia.org/wiki/Millard_Fillmore',
            party: "Whig",
            birth: '1800-01-07',
            death: '1874-03-08',
            birthPlace: 'Summerhill, New York, USA',
            deathPlace: 'Buffalo, New York',
            religion: [ "Unitarian" ]
        },
        {   label: 'Franklin Pierce',
            type: 'President',
            presidency: 14,
            index: 14,
            term: [ 17 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Franklin_Pierce.jpg/100px-Franklin_Pierce.jpg',
            url: 'http://en.wikipedia.org/wiki/Franklin_Pierce',
            party: "Democratic",
            birth: '1804-11-23',
            death: '1869-10-08',
            birthPlace: 'Hillsborough, New Hampshire, USA',
            deathPlace: 'Concord, New Hampshire',
            religion: [ "Episcopal" ]
        },
        {   label: 'James Buchanan',
            type: 'President',
            presidency: 15,
            index: 15,
            term: [ 18 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/James_Buchanan.jpg/100px-James_Buchanan.jpg',
            url: 'http://en.wikipedia.org/wiki/James_Buchanan',
            party: "Democratic",
            birth: '1791-04-23',
            death: '1868-06-01',
            birthPlace: 'Cove Gap, Pennsylvania, USA',
            deathPlace: 'Lancaster, Pennsylvania',
            religion: [ "Presbyterian" ]
        },
        {   label: 'Abraham Lincoln',
            type: 'President',
            presidency: 16,
            index: 16,
            term: [ 19, 20 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Abraham_Lincoln_head_on_shoulders_photo_portrait.jpg/100px-Abraham_Lincoln_head_on_shoulders_photo_portrait.jpg',
            url: 'http://en.wikipedia.org/wiki/Abraham_Lincoln',
            party: "Republican",
            birth: '1809-02-12',
            death: '1865-04-15',
            birthPlace: 'Hardin County, Kentucky, USA',
            deathPlace: 'Washington, D.C.',
            religion: [ "no affiliation" ]
        },
        {   label: 'Andrew Johnson',
            type: 'President',
            presidency: 17,
            index: 17,
            term: [ 20 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Pres_andrew_johnson.jpg/100px-Pres_andrew_johnson.jpg',
            url: 'http://en.wikipedia.org/wiki/Andrew_Johnson',
            party: "Democratic",
            birth: '1808-12-29',
            death: '1875-07-31',
            birthPlace: 'Raleigh, North Carolina, USA',
            deathPlace: 'Greeneville, Tennessee',
            religion: [ "no affiliation" ]
        },
        {   label: 'Ulysses Grant',
            type: 'President',
            presidency: 18,
            index: 18,
            term: [ 21, 22 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Ulysses_Grant_1870-1880.jpg/100px-Ulysses_Grant_1870-1880.jpg',
            url: 'http://en.wikipedia.org/wiki/Ulysses_Grant',
            party: "Republican",
            birth: '1822-04-27',
            death: '1885-07-23',
            birthPlace: 'Point Pleasant, Ohio, USA',
            deathPlace: 'Mount McGregor, New York',
            religion: [ "never baptized" ]
        },
        {   label: 'Rutherford Hayes',
            type: 'President',
            presidency: 19,
            index: 19,
            term: [ 23 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/9/97/President_Rutherford_Hayes_1870_-_1880.jpg/100px-President_Rutherford_Hayes_1870_-_1880.jpg',
            url: 'http://en.wikipedia.org/wiki/Rutherford_Hayes',
            party: "Republican",
            birth: '1822-10-04',
            death: '1893-01-17',
            birthPlace: 'Delaware, Ohio, USA',
            deathPlace: 'Fremont, Ohio',
            religion: [ "no affiliation" ]
        },
        {   label: 'James Garfield',
            type: 'President',
            presidency: 20,
            index: 20,
            term: [ 24 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/James_Abram_Garfield%2C_photo_portrait_seated.jpg/100px-James_Abram_Garfield%2C_photo_portrait_seated.jpg',
            url: 'http://en.wikipedia.org/wiki/James_Garfield',
            party: "Republican",
            birth: '1831-11-19',
            death: '1881-09-19',
            birthPlace: 'Moreland Hills, Ohio, USA',
            deathPlace: 'Elberon (Long Branch), New Jersey',
            religion: [ "Church of Christ" ]
        },
        {   label: 'Chester Arthur',
            type: 'President',
            presidency: 21,
            index: 21,
            term: [ 24 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Chester_Alan_Arthur.jpg/100px-Chester_Alan_Arthur.jpg',
            url: 'http://en.wikipedia.org/wiki/Chester_Arthur',
            party: "Republican",
            birth: '1830-10-05',
            death: '1886-11-18',
            birthPlace: 'Fairfield, Vermont, USA',
            deathPlace: 'New York City, New York',
            religion: [ "Episcopal" ]
        },
        {   label: 'Grover Cleveland',
            type: 'President',
            presidency: [ 22, 24 ],
            index: 22,
            term: [ 25, 27 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/9/91/President_Grover_Cleveland.jpg/100px-President_Grover_Cleveland.jpg',
            url: 'http://en.wikipedia.org/wiki/Grover_Cleveland',
            party: "Democratic",
            birth: '1837-03-18',
            death: '1908-06-24',
            birthPlace: 'Caldwell, New Jersey, USA',
            deathPlace: 'Princeton, New Jersey',
            religion: [ "Presbyterian" ]
        },
        {   label: 'Benjamin Harrison',
            type: 'President',
            presidency: 23,
            index: 23,
            term: [ 26 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg/100px-Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg',
            url: 'http://en.wikipedia.org/wiki/Benjamin_Harrison',
            party: "Republican",
            birth: '1833-08-20',
            death: '1901-03-13',
            birthPlace: 'North Bend, Ohio, USA',
            deathPlace: 'Indianapolis, Indiana',
            religion: [ "Presbyterian" ]
        },
        {   label: 'William McKinley',
            type: 'President',
            presidency: 25,
            index: 24,
            term: [ 28, 29 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Mckinley.jpg/100px-Mckinley.jpg',
            url: 'http://en.wikipedia.org/wiki/William_McKinley',
            party: "Republican",
            birth: '1843-01-29',
            death: '1901-09-14',
            birthPlace: 'Niles, Ohio, USA',
            deathPlace: 'Buffalo, New York',
            religion: [ "Methodist" ]
        },
        {   label: 'Theodore Roosevelt',
            type: 'President',
            presidency: 26,
            index: 25,
            term: [ 29, 30 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/President_Theodore_Roosevelt%2C_1904.jpg/100px-President_Theodore_Roosevelt%2C_1904.jpg',
            url: 'http://en.wikipedia.org/wiki/Theodore_Roosevelt',
            party: "Republican",
            birth: '1858-10-27',
            death: '1919-01-06',
            birthPlace: 'New York City, New York, USA',
            deathPlace: 'Oyster Bay, New York',
            religion: [ "Dutch Reformed" ]
        },
        {   label: 'William Taft',
            type: 'President',
            presidency: 27,
            index: 26,
            term: [ 31 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/William_Howard_Taft%2C_Bain_bw_photo_portrait%2C_1908.jpg/100px-William_Howard_Taft%2C_Bain_bw_photo_portrait%2C_1908.jpg',
            url: 'http://en.wikipedia.org/wiki/William_Taft',
            party: "Republican",
            birth: '1857-09-15',
            death: '1930-03-08',
            birthPlace: 'Cincinnati, Ohio, USA',
            deathPlace: 'Washington, D.C.',
            religion: [ "Unitarian" ]
        },
        {   label: 'Woodrow Wilson',
            type: 'President',
            presidency: 28,
            index: 27,
            term: [ 32, 33 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/President_Woodrow_Wilson_portrait_December_2_1912.jpg/100px-President_Woodrow_Wilson_portrait_December_2_1912.jpg',
            url: 'http://en.wikipedia.org/wiki/Woodrow_Wilson',
            party: "Democratic",
            birth: '1856-12-28',
            death: '1924-02-03',
            birthPlace: 'Staunton, Virginia, USA',
            deathPlace: 'Washington, D.C.',
            religion: [ "Presbyterian" ]
        },
        {   label: 'Warren Harding',
            type: 'President',
            presidency: 29,
            index: 28,
            term: [ 34 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Warren_G_Harding_portrait_as_senator_June_1920.jpg/100px-Warren_G_Harding_portrait_as_senator_June_1920.jpg',
            url: 'http://en.wikipedia.org/wiki/Warren_Harding',
            party: "Republican",
            birth: '1865-11-02',
            death: '1923-08-02',
            birthPlace: 'Blooming Grove, Ohio, USA',
            deathPlace: 'San Francisco, California',
            religion: [ "Baptist" ]
        },
        {   label: 'Calvin Coolidge',
            type: 'President',
            presidency: 30,
            index: 29,
            term: [ 34, 35 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Calvin_Coolidge_photo_portrait_head_and_shoulders.jpg/100px-Calvin_Coolidge_photo_portrait_head_and_shoulders.jpg',
            url: 'http://en.wikipedia.org/wiki/Calvin_Coolidge',
            party: "Republican",
            birth: '1872-07-04',
            death: '1933-01-05',
            birthPlace: 'Plymouth, Vermont, USA',
            deathPlace: 'Northampton, Massachusetts',
            religion: [ "Congregationalist" ]
        },
        {   label: 'Herbert Hoover',
            type: 'President',
            presidency: 31,
            index: 30,
            term: [ 36 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/HerbertHoover.jpg/100px-HerbertHoover.jpg',
            url: 'http://en.wikipedia.org/wiki/Herbert_Hoover',
            party: "Republican",
            birth: '1874-08-10',
            death: '1964-10-20',
            birthPlace: 'West Branch, Iowa, USA',
            deathPlace: 'New York City, New York',
            religion: [ "Quaker" ]
        },
        {   label: 'Franklin D. Roosevelt',
            type: 'President',
            presidency: 32,
            index: 31,
            term: [ 37, 38, 39, 40 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/FDR_in_1933.jpg/100px-FDR_in_1933.jpg',
            url: 'http://en.wikipedia.org/wiki/Franklin_D._Roosevelt',
            party: "Democratic",
            birth: '1882-01-30',
            death: '1945-04-12',
            birthPlace: 'Hyde Park, New York, USA',
            deathPlace: 'Warm Springs, Georgia',
            religion: [ "Episcopal" ]
        },
        {   label: 'Harry Truman',
            type: 'President',
            presidency: 33,
            index: 32,
            term: [ 40, 41 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Harry-truman.jpg/100px-Harry-truman.jpg',
            url: 'http://en.wikipedia.org/wiki/Harry_Truman',
            party: "Democratic",
            birth: '1884-05-08',
            death: '1972-12-26',
            birthPlace: 'Lamar, Missouri, USA',
            deathPlace: 'Kansas City, Missouri',
            religion: [ "Baptist" ]
        },
        {   label: 'Dwight Eisenhower',
            type: 'President',
            presidency: 34,
            index: 33,
            term: [ 42, 43 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Eisenhower_official.jpg/100px-Eisenhower_official.jpg',
            url: 'http://en.wikipedia.org/wiki/Dwight_Eisenhower',
            party: "Republican",
            birth: '1890-10-14',
            death: '1969-03-28',
            birthPlace: 'Denison, Texas, USA',
            deathPlace: 'Washington, D.C.',
            religion: [ "Presbyterian" ]
        },
        {   label: 'John F. Kennedy',
            type: 'President',
            presidency: 35,
            index: 34,
            term: [ 44 ],
            dieInOffice: 'yes',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/John_F_Kennedy.jpg/100px-John_F_Kennedy.jpg',
            url: 'http://en.wikipedia.org/wiki/John_F._Kennedy',
            party: "Democratic",
            birth: '1917-05-29',
            death: '1963-11-22',
            birthPlace: 'Brookline, Massachusetts, USA',
            deathPlace: 'Dallas, Texas',
            religion: [ "Roman Catholic" ]
        },
        {   label: 'Lyndon Johnson',
            type: 'President',
            presidency: 36,
            index: 35,
            term: [ 44, 45 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Lbj2.jpg/100px-Lbj2.jpg',
            url: 'http://en.wikipedia.org/wiki/Lyndon_B._Johnson',
            party: "Democratic",
            birth: '1908-08-27',
            death: '1973-01-22',
            birthPlace: 'Stonewall, Texas, USA',
            deathPlace: 'Stonewall, Texas',
            religion: [ "Disciple of Christ" ]
        },
        {   label: 'Richard Nixon',
            type: 'President',
            presidency: 37,
            index: 36,
            term: [ 46, 47 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nixon_30-0316a.gif/100px-Nixon_30-0316a.gif',
            url: 'http://en.wikipedia.org/wiki/Richard_Nixon',
            party: "Republican",
            birth: '1913-01-09',
            death: '1994-04-22',
            birthPlace: 'Yorba Linda, California, USA',
            deathPlace: 'New York City, New York',
            religion: [ "Quaker" ]
        },
        {   label: 'Gerald Ford',
            type: 'President',
            presidency: 38,
            index: 37,
            term: [ 47 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Gerald_Ford.jpg/100px-Gerald_Ford.jpg',
            url: 'http://en.wikipedia.org/wiki/Gerald_Ford',
            party: "Republican",
            birth: '1913-07-14',
            death: '2006-12-26',
            birthPlace: 'Omaha, Nebraska, USA',
            deathPlace: 'Rancho Mirage, California, USA',
            religion: [ "Episcopal" ]
        },
        {   label: 'Jimmy Carter',
            type: 'President',
            presidency: 39,
            index: 38,
            term: [ 48 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Jimmy_Carter.jpg/100px-Jimmy_Carter.jpg',
            url: 'http://en.wikipedia.org/wiki/Jimmy_Carter',
            party: "Democratic",
            birth: '1924-10-01',
            birthPlace: 'Plains, Georgia, USA',
            religion: [ "Baptist" ]
        },
        {   label: 'Ronald Reagan',
            type: 'President',
            presidency: 40,
            index: 39,
            term: [ 49, 50 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Official_Portrait_of_President_Reagan_1981.jpg/100px-Official_Portrait_of_President_Reagan_1981.jpg',
            url: 'http://en.wikipedia.org/wiki/Ronald_Reagan',
            party: "Republican",
            birth: '1911-02-06',
            death: '2004-06-05',
            birthPlace: 'Tampico, Illinois, USA',
            deathPlace: 'Bel-Air, California',
            religion: [ "Presbyterian" ]
        },
        {   label: 'George H.W. Bush',
            type: 'President',
            presidency: 41,
            index: 40,
            term: [ 51 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/George_H._W._Bush%2C_President_of_the_United_States%2C_1989_official_portrait.jpg/100px-George_H._W._Bush%2C_President_of_the_United_States%2C_1989_official_portrait.jpg',
            url: 'http://en.wikipedia.org/wiki/George_H._W._Bush',
            party: "Republican",
            birth: '1924-06-12',
            birthPlace: 'Milton, Massachusetts, USA',
            religion: [ "Episcopal" ]
        },
        {   label: 'Bill Clinton',
            type: 'President',
            presidency: 42,
            index: 41,
            term: [ 52, 53 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Bill_Clinton.jpg/100px-Bill_Clinton.jpg',
            url: 'http://en.wikipedia.org/wiki/Bill_Clinton',
            party: "Democratic",
            birth: '1946-08-19',
            birthPlace: 'Hope, Arkansas, USA',
            religion: [ "Baptist" ]
        },
        {   label: 'George W. Bush',
            type: 'President',
            presidency: 43,
            index: 42,
            term: [ 54, 55 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/George-W-Bush.jpeg/100px-George-W-Bush.jpeg',
            url: 'http://en.wikipedia.org/wiki/George_W._Bush',
            party: "Republican",
            birth: '1946-07-06',
            birthPlace: 'New Haven, Connecticut, USA',
            religion: [ "Methodist" ]
        },
        {   label: 'Barack Obama',
            type: 'President',
            presidency: 44,
            index: 43,
            term: [ 56 ],
            dieInOffice: 'no',
            imageURL: 'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Official_portrait_of_Barack_Obama.jpg/100px-Official_portrait_of_Barack_Obama.jpg',
            url: 'http://en.wikipedia.org/wiki/Barack_Obama',
            party: "Democratic",
            birth: '1961-08-04',
            birthPlace: 'Honolulu, Hawaii, USA',
            religion: [ "Christian" ]
        },        
        {   label: '1',
            type: 'Presidency',
            index: 1,
            inDate: '1789-04-30',
            outDate: '1797-03-04'
        },
        {   label: '2',
            type: 'Presidency',
            index: 2,
            inDate: '1797-03-04',
            outDate: '1801-03-04'
        },
        {   label: '3',
            type: 'Presidency',
            index: 3,
            inDate: '1801-03-04',
            outDate: '1809-03-04'
        },
        {   label: '4',
            type: 'Presidency',
            index: 4,
            inDate: '1809-03-04',
            outDate: '1817-03-04'
        },
        {   label: '5',
            type: 'Presidency',
            index: 5,
            inDate: '1817-03-04',
            outDate: '1825-03-04'
        },
        {   label: '6',
            type: 'Presidency',
            index: 6,
            inDate: '1825-03-04',
            outDate: '1829-03-04'
        },
        {   label: '7',
            type: 'Presidency',
            index: 7,
            inDate: '1829-03-04',
            outDate: '1837-03-04'
        },
        {   label: '8',
            type: 'Presidency',
            index: 8,
            inDate: '1837-03-04',
            outDate: '1841-03-04'
        },
        {   label: '9',
            type: 'Presidency',
            index: 9,
            inDate: '1841-03-04',
            outDate: '1841-04-04'
        },
        {   label: '10',
            type: 'Presidency',
            index: 10,
            inDate: '1841-04-04',
            outDate: '1845-03-04'
        },
        {   label: '11',
            type: 'Presidency',
            index: 11,
            inDate: '1845-03-04',
            outDate: '1849-03-04'
        },
        {   label: '12',
            type: 'Presidency',
            index: 12,
            inDate: '1849-03-04',
            outDate: '1850-07-09'
        },
        {   label: '13',
            type: 'Presidency',
            index: 13,
            inDate: '1850-07-09',
            outDate: '1853-03-04'
        },
        {   label: '14',
            type: 'Presidency',
            index: 14,
            inDate: '1853-03-04',
            outDate: '1857-03-04'
        },
        {   label: '15',
            type: 'Presidency',
            index: 15,
            inDate: '1857-03-04',
            outDate: '1861-03-04'
        },
        {   label: '16',
            type: 'Presidency',
            index: 16,
            inDate: '1861-03-04',
            outDate: '1865-04-15'
        },
        {   label: '17',
            type: 'Presidency',
            index: 17,
            inDate: '1865-04-15',
            outDate: '1869-03-04'
        },
        {   label: '18',
            type: 'Presidency',
            index: 18,
            inDate: '1869-03-04',
            outDate: '1877-03-04'
        },
        {   label: '19',
            type: 'Presidency',
            index: 19,
            inDate: '1877-03-04',
            outDate: '1881-03-04'
        },
        {   label: '20',
            type: 'Presidency',
            index: 20,
            inDate: '1881-03-04',
            outDate: '1881-09-19'
        },
        {   label: '21',
            type: 'Presidency',
            index: 21,
            inDate: '1881-09-19',
            outDate: '1885-03-04'
        },
        {   label: '22',
            type: 'Presidency',
            index: 22,
            inDate: '1885-03-04',
            outDate: '1889-03-04'
        },
        {   label: '23',
            type: 'Presidency',
            index: 23,
            inDate: '1889-03-04',
            outDate: '1893-03-04'
        },
        {   label: '24',
            type: 'Presidency',
            index: 24,
            inDate: '1893-03-04',
            outDate: '1897-03-04'
        },
        {   label: '25',
            type: 'Presidency',
            index: 25,
            inDate: '1897-03-04',
            outDate: '1901-09-14'
        },
        {   label: '26',
            type: 'Presidency',
            index: 26,
            inDate: '1901-09-14',
            outDate: '1909-03-04'
        },
        {   label: '27',
            type: 'Presidency',
            index: 27,
            inDate: '1909-03-04',
            outDate: '1913-03-04'
        },
        {   label: '28',
            type: 'Presidency',
            index: 28,
            inDate: '1913-03-04',
            outDate: '1921-03-04'
        },
        {   label: '29',
            type: 'Presidency',
            index: 29,
            inDate: '1921-03-04',
            outDate: '1923-08-02'
        },
        {   label: '30',
            type: 'Presidency',
            index: 30,
            inDate: '1923-08-02',
            outDate: '1929-03-04'
        },
        {   label: '31',
            type: 'Presidency',
            index: 31,
            inDate: '1929-03-04',
            outDate: '1933-03-04'
        },
        {   label: '32',
            type: 'Presidency',
            index: 32,
            inDate: '1933-03-04',
            outDate: '1945-04-12'
        },
        {   label: '33',
            type: 'Presidency',
            index: 33,
            inDate: '1945-04-12',
            outDate: '1953-01-20'
        },
        {   label: '34',
            type: 'Presidency',
            index: 34,
            inDate: '1953-01-20',
            outDate: '1961-01-20'
        },
        {   label: '35',
            type: 'Presidency',
            index: 35,
            inDate: '1961-01-20',
            outDate: '1963-11-22'
        },
        {   label: '36',
            type: 'Presidency',
            index: 36,
            inDate: '1963-11-22',
            outDate: '1969-01-20'
        },
        {   label: '37',
            type: 'Presidency',
            index: 37,
            inDate: '1969-01-20',
            outDate: '1974-08-09'
        },
        {   label: '38',
            type: 'Presidency',
            index: 38,
            inDate: '1974-08-09',
            outDate: '1977-01-20'
        },
        {   label: '39',
            type: 'Presidency',
            index: 39,
            inDate: '1977-01-20',
            outDate: '1981-01-20'
        },
        {   label: '40',
            type: 'Presidency',
            index: 40,
            inDate: '1981-01-20',
            outDate: '1989-01-20'
        },
        {   label: '41',
            type: 'Presidency',
            index: 41,
            inDate: '1989-01-20',
            outDate: '1993-01-20'
        },
        {   label: '42',
            type: 'Presidency',
            index: 42,
            inDate: '1993-01-20',
            outDate: '2001-01-20'
        },
        {   label: '43',
            type: 'Presidency',
            index: 43,
            inDate: '2001-01-20',
            outDate: '2009-01-20'
        },
        {   label: '44',
            type: 'Presidency',
            index: 44,
            inDate: '2009-01-20'
        },
        
        {   id: 'George Washington',
            birthLatLng: '37.585241,-77.497343'
        },
        {   id: 'John Adams',
            birthLatLng: '42.222222,-71'
        },
        {   id: 'Thomas Jefferson',
            birthLatLng: '37.585241,-77.497343'
        },
        {   id: 'James Madison',
            birthLatLng: '37.585241,-77.497343'
        },
        {   id: 'James Monroe',
            birthLatLng: '37.585241,-77.497343'
        },
        {   id: 'John Quincy Adams',
            birthLatLng: '42.222222,-71'
        },
        {   id: 'Andrew Jackson',
            birthLatLng: '34.052298,-80.978488'
        },
        {   id: 'Martin Van Buren',
            birthLatLng: '42.395278,-73.698333'
        },
        {   id: 'William Harrison',
            birthLatLng: '37.585241,-77.497343'
        },
        {   id: 'John Tyler',
            birthLatLng: '37.585241,-77.497343'
        },
        {   id: 'James Polk',
            birthLatLng: '35.826542,-78.646372'
        },
        {   id: 'Zachary Taylor',
            birthLatLng: '38.170833,-78.281944'
        },
        {   id: 'Millard Fillmore',
            birthLatLng: '42.654167,-76.411667'
        },
        {   id: 'Franklin Pierce',
            birthLatLng: '43.114167,-71.899444'
        },
        {   id: 'James Buchanan',
            birthLatLng: '39.827778,-77.903611'
        },
        {   id: 'Abraham Lincoln',
            birthLatLng: '38.210509,-84.875859'
        },
        {   id: 'Andrew Johnson',
            birthLatLng: '35.771944,-78.638889'
        },
        {   id: 'Ulysses Grant',
            birthLatLng: '40.00218,-82.988826'
        },
        {   id: 'Rutherford Hayes',
            birthLatLng: '40.298611,-83.068056'
        },
        {   id: 'James Garfield',
            birthLatLng: '41.447778,-81.427778'
        },
        {   id: 'Chester Arthur',
            birthLatLng: '44.801944,-72.946111'
        },
        {   id: 'Grover Cleveland',
            birthLatLng: '40.839722,-74.276944'
        },
        {   id: 'Benjamin Harrison',
            birthLatLng: '39.1525,-84.748056'
        },
        {   id: 'William McKinley',
            birthLatLng: '41.182778,-80.765556'
        },
        {   id: 'Theodore Roosevelt',
            birthLatLng: '40.714167,-74.006389'
        },
        {   id: 'William Taft',
            birthLatLng: '39.161944,-84.456944'
        },
        {   id: 'Woodrow Wilson',
            birthLatLng: '38.149444,-79.071944'
        },
        {   id: 'Warren Harding',
            birthLatLng: '40.733611,-82.79'
        },
        {   id: 'Calvin Coolidge',
            birthLatLng: '43.535833,-72.721944'
        },
        {   id: 'Herbert Hoover',
            birthLatLng: '41.665,-91.34'
        },
        {   id: 'Franklin D. Roosevelt',
            birthLatLng: '41.784722,-73.933611'
        },
        {   id: 'Harry Truman',
            birthLatLng: '37.495,-94.276389'
        },
        {   id: 'Dwight Eisenhower',
            birthLatLng: '33.755556,-96.536389'
        },
        {   id: 'John F. Kennedy',
            birthLatLng: '42.331667,-71.121667'
        },
        {   id: 'Lyndon Johnson',
            birthLatLng: '30.235833,-98.664167'
        },
        {   id: 'Richard Nixon',
            birthLatLng: '33.888611,-117.812222'
        },
        {   id: 'Gerald Ford',
            birthLatLng: '41.258611,-95.9375'
        },
        {   id: 'Jimmy Carter',
            birthLatLng: '32.033889,-84.392778'
        },
        {   id: 'Ronald Reagan',
            birthLatLng: '41.630278,-89.786111'
        },
        {   id: 'George H.W. Bush',
            birthLatLng: '42.249444,-71.066667'
        },
        {   id: 'Bill Clinton',
            birthLatLng: '33.666944,-93.591389'
        },
        {   id: 'George W. Bush',
            birthLatLng: '41.308056,-72.928611'
        },
        {   id: 'Barack Obama',
            birthLatLng: '21.3069,-157.8583'
        },
            
        {   id: 'George Washington',
            deathLatLng: '38.707778,-77.086389'
        },
        {   id: 'John Adams',
            deathLatLng: '42.252778,-71.002778'
        },
        {   id: 'Thomas Jefferson',
            deathLatLng: '38.029167,-78.476944'
        },
        {   id: 'James Madison',
            deathLatLng: '37.821111,-77.684722'
        },
        {   id: 'James Monroe',
            deathLatLng: '40.714167,-74.006389'
        },
        {   id: 'John Quincy Adams',
            deathLatLng: '38.895,-77.036667'
        },
        {   id: 'Andrew Jackson',
            deathLatLng: '36.165833,-86.784444'
        },
        {   id: 'Martin Van Buren',
            deathLatLng: '42.395278,-73.698333'
        },
        {   id: 'William Harrison',
            deathLatLng: '38.895,-77.036667'
        },
        {   id: 'John Tyler',
            deathLatLng: '37.553611,-77.460556'
        },
        {   id: 'James Polk',
            deathLatLng: '36.165833,-86.784444'
        },
        {   id: 'Zachary Taylor',
            deathLatLng: '38.895,-77.036667'
        },
        {   id: 'Millard Fillmore',
            deathLatLng: '42.886389,-78.878611'
        },
        {   id: 'Franklin Pierce',
            deathLatLng: '43.208056,-71.538056'
        },
        {   id: 'James Buchanan',
            deathLatLng: '40.037778,-76.305833'
        },
        {   id: 'Abraham Lincoln',
            deathLatLng: '38.895,-77.036667'
        },
        {   id: 'Andrew Johnson',
            deathLatLng: '36.163056,-82.831111'
        },
        {   id: 'Ulysses Grant',
            deathLatLng: '40.714167,-74.006389'
        },
        {   id: 'Rutherford Hayes',
            deathLatLng: '41.350278,-83.121944'
        },
        {   id: 'James Garfield',
            deathLatLng: '40.234385,-74.715664'
        },
        {   id: 'Chester Arthur',
            deathLatLng: '40.714167,-74.006389'
        },
        {   id: 'Grover Cleveland',
            deathLatLng: '40.348611,-74.659444'
        },
        {   id: 'Benjamin Harrison',
            deathLatLng: '39.768333,-86.158056'
        },
        {   id: 'William McKinley',
            deathLatLng: '42.886389,-78.878611'
        },
        {   id: 'Theodore Roosevelt',
            deathLatLng: '40.921667,-73.505833'
        },
        {   id: 'William Taft',
            deathLatLng: '38.895,-77.036667'
        },
        {   id: 'Woodrow Wilson',
            deathLatLng: '38.895,-77.036667'
        },
        {   id: 'Warren Harding',
            deathLatLng: '37.775,-122.418333'
        },
        {   id: 'Calvin Coolidge',
            deathLatLng: '42.325,-72.641667'
        },
        {   id: 'Herbert Hoover',
            deathLatLng: '40.714167,-74.006389'
        },
        {   id: 'Franklin D. Roosevelt',
            deathLatLng: '32.890278,-84.681111'
        },
        {   id: 'Harry Truman',
            deathLatLng: '39.099722,-94.578333'
        },
        {   id: 'Dwight Eisenhower',
            deathLatLng: '38.895,-77.036667'
        },
        {   id: 'John F. Kennedy',
            deathLatLng: '32.783333,-96.8'
        },
        {   id: 'Lyndon Johnson',
            deathLatLng: '30.235833,-98.664167'
        },
        {   id: 'Richard Nixon',
            deathLatLng: '40.714167,-74.006389'
        },
        {   id: 'Ronald Reagan',
            deathLatLng: '34.101111,-118.453056' 
        },
        {   id: 'Gerald Ford',
            deathLatLng: '33.739713,-116.411819'
        }
    ]
}
