{
    "items": [
        {   "label":          "John Davison Rockefeller",
            "type":           "Billionaire",
            "number":         "1",
            "ageAtPeak":      "97",
            "ageAtDeath":     "97",
            "wealth":         "189.7",
            "origin":         "Richford, NY",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Standard Oil Company",
            "latLng":         "42.35623,-76.2007",
            "label-link":     "/axowiki/index.php?title=John_Davison_Rockefeller&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Standard_Oil_Company&action=edit"
        },
        {   "label":          "Cornelius Vanderbilt",
            "type":           "Billionaire",
            "number":         "2",
            "ageAtPeak":      "82",
            "ageAtDeath":     "82",
            "wealth":         "150.6",
            "origin":         "New York City, NY",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Railroad, shipping",
            "latLng":         "40.71449,-74.00713",
            "label-link":     "/axowiki/index.php?title=Cornelius_Vanderbilt&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Railroad&action=edit"
        },
        {   "label":          "Henry Ford",
            "type":           "Billionaire",
            "number":         "3",
            "ageAtPeak":      "57",
            "ageAtDeath":     "83",
            "wealth":         "140.9",
            "origin":         "Detroit, MI",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Ford Motor Company",
            "latLng":         "42.33162,-83.04779",
            "label-link":     "/axowiki/index.php?title=Henry_Ford&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Ford_Motor_Company&action=edit"
        },
        {   "label":          "H. L. Hunt",
            "type":           "Billionaire",
            "number":         "4",
            "ageAtPeak":      "75",
            "ageAtDeath":     "85",
            "wealth":         "122.0",
            "origin":         "Ramsey, IL",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Hunt Refining Company",
            "latLng":         "39.14464,-89.10827",
            "label-link":     "/axowiki/index.php?title=H._L._Hunt&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Hunt_Refining_Company&action=edit"
        },
        {   "label":          "Andrew Carnegie",
            "type":           "Billionaire",
            "number":         "5",
            "ageAtPeak":      "75",
            "ageAtDeath":     "83",
            "wealth":         "120.0",
            "origin":         "Scotland",
            "residence":      "United States",
            "origin-country": "Scotland",
            "company":        "Carnegie Steel Company",
            "latLng":         "33.647491,-98.461905",
            "label-link":     "/axowiki/index.php?title=Andrew_Carnegie&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Carnegie_Steel_Company&action=edit"
        },
        {   "label":          "John Jacob Astor",
            "type":           "Billionaire",
            "number":         "6",
            "ageAtPeak":      "84",
            "ageAtDeath":     "84",
            "wealth":         "103.4",
            "origin":         "Walldorf, Germany",
            "residence":      "United States",
            "origin-country": "Germany",
            "company":        "American Fur Company",
            "latLng":         "50.005067,8.574268",
            "label-link":     "/axowiki/index.php?title=John_Jacob_Astor&action=edit",
            "origin-link":    "/axowiki/index.php?title=Germany&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=American_Fur_Company&action=edit"
        },
        {   "label":          "William Henry Gates III",
            "type":           "Billionaire",
            "number":         "7",
            "ageAtPeak":      "44",
            "ageAtDeath":     "51",
            "wealth":         "100.0",
            "origin":         "Seattle, WA",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Microsoft",
            "latLng":         "47.60342,-122.32971",
            "label-link":     "/axowiki/index.php?title=William_Henry_Gates_III&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Microsoft&action=edit"
        },
        {   "label":          "Carlos Slim Helu",
            "type":           "Billionaire",
            "number":         "8",
            "ageAtPeak":      "67",
            "ageAtDeath":     "67",
            "wealth":         "68.7",
            "origin":         "Mexico City, Mexico",
            "residence":      "Mexico",
            "origin-country": "Mexico",
            "company":        "Telmex",
            "latLng":         "19.410636,-99.130588",
            "label-link":     "/axowiki/index.php?title=Carlos_Slim_Helu&action=edit",
            "origin-link":    "/axowiki/index.php?title=Mexico&action=edit",
            "residence-link": "/axowiki/index.php?title=Mexico&action=edit",
            "company-link":   "/axowiki/index.php?title=Telmex&action=edit"
        },
        {   "label":          "Larry Ellison",
            "type":           "Billionaire",
            "number":         "9",
            "ageAtPeak":      "55",
            "ageAtDeath":     "61",
            "wealth":         "58.0",
            "origin":         "New York City, NY",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Oracle Corporation",
            "latLng":         "40.71449,-74.00713",
            "label-link":     "/axowiki/index.php?title=Larry_Ellison&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Oracle_Corporation&action=edit"
        },
        {   "label":          "Warren Buffett",
            "type":           "Billionaire",
            "number":         "10",
            "ageAtPeak":      "76",
            "ageAtDeath":     "76",
            "wealth":         "52.4",
            "origin":         "Omaha, NE",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Berkshire Hathaway",
            "latLng":         "41.2607,-95.93989",
            "label-link":     "/axowiki/index.php?title=Warren_Buffett&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Berkshire_Hathaway&action=edit"
        },
        {   "label":          "Howard Hughes",
            "type":           "Billionaire",
            "number":         "12",
            "ageAtPeak":      "45",
            "ageAtDeath":     "50",
            "wealth":         "41.4",
            "origin":         "Houston, TX",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "TWA",
            "latLng":         "29.76047,-95.36982",
            "label-link":     "/axowiki/index.php?title=Howard_Hughes&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=TWA&action=edit"
        },
        {   "label":          "Paul Allen",
            "type":           "Billionaire",
            "number":         "13",
            "ageAtPeak":      "48",
            "ageAtDeath":     "53",
            "wealth":         "40.0",
            "origin":         "Seattle, WA",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Microsoft",
            "latLng":         "47.60342,-122.32971",
            "label-link":     "/axowiki/index.php?title=Paul_Allen&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Microsoft&action=edit"
        },
        {   "label":          "John Werner Kluge",
            "type":           "Billionaire",
            "number":         "14",
            "ageAtPeak":      "70",
            "ageAtDeath":     "92",
            "wealth":         "40.0",
            "origin":         "Chemnitz, Germany",
            "residence":      "United States",
            "origin-country": "Germany",
            "company":        "Metropolitan Broadcasting Company",
            "latLng":         "50.832503,12.924694",
            "label-link":     "/axowiki/index.php?title=John_Werner_Kluge&action=edit",
            "origin-link":    "/axowiki/index.php?title=Germany&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Metropolitan_Broadcasting_Company&action=edit"
        },
        {   "label":          "Sultan Hassanal Bolkiah",
            "type":           "Billionaire",
            "number":         "15",
            "ageAtPeak":      "51",
            "ageAtDeath":     "60",
            "wealth":         "38.0",
            "origin":         "Brunei",
            "residence":      "Brunei",
            "origin-country": "Brunei",
            "company":        "Kral",
            "latLng":         "4.525134,114.71545",
            "label-link":     "/axowiki/index.php?title=Sultan_Hassanal_Bolkiah&action=edit",
            "origin-link":    "/axowiki/index.php?title=Brunei&action=edit",
            "residence-link": "/axowiki/index.php?title=Brunei&action=edit",
            "company-link":   "/axowiki/index.php?title=Kral&action=edit"
        },
        {   "label":          "Ingvar Kamprad",
            "type":           "Billionaire",
            "number":         "16",
            "ageAtPeak":      "80",
            "ageAtDeath":     "80",
            "wealth":         "33.0",
            "origin":         "Sweden",
            "residence":      "Switzerland",
            "origin-country": "Sweden",
            "company":        "IKEA",
            "latLng":         "62.098297,17.384786",
            "label-link":     "/axowiki/index.php?title=Ingvar_Kamprad&action=edit",
            "origin-link":    "/axowiki/index.php?title=Sweden&action=edit",
            "residence-link": "/axowiki/index.php?title=Switzerland&action=edit",
            "company-link":   "/axowiki/index.php?title=IKEA&action=edit"
        },
        {   "label":          "Lakshmi Mittal",
            "type":           "Billionaire",
            "number":         "30",
            "ageAtPeak":      "54",
            "ageAtDeath":     "54",
            "wealth":         "32.0",
            "origin":         "India",
            "residence":      "England",
            "origin-country": "India",
            "company":        "Mittal Steel Company",
            "latLng":         "21.125673,82.397136",
            "label-link":     "/axowiki/index.php?title=Lakshmi_Mittal&action=edit",
            "origin-link":    "/axowiki/index.php?title=India&action=edit",
            "residence-link": "/axowiki/index.php?title=England&action=edit",
            "company-link":   "/axowiki/index.php?title=Mittal_Steel_Company&action=edit"
        },
        {   "label":          "J. Paul Getty",
            "type":           "Billionaire",
            "number":         "18",
            "ageAtPeak":      "83",
            "ageAtDeath":     "83",
            "wealth":         "27.3",
            "origin":         "Minneapolis, MN",
            "residence":      "England",
            "origin-country": "United States",
            "company":        "Getty Oil Company",
            "latLng":         "44.9785,-93.26529",
            "label-link":     "/axowiki/index.php?title=J._Paul_Getty&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=England&action=edit",
            "company-link":   "/axowiki/index.php?title=Getty_Oil_Company&action=edit"
        },
        {   "label":          "Theo Albrecht & Karl Albrecht",
            "type":           "Billionaire",
            "number":         "19",
            "ageAtPeak":      "-",
            "ageAtDeath":     "-",
            "wealth":         "26.8",
            "origin":         "Germany",
            "residence":      "Germany",
            "origin-country": "Germany",
            "company":        "Aldi",
            "latLng":         "51.163475,10.454239",
            "label-link":     "/axowiki/index.php?title=Theo_Albrecht&action=edit",
            "origin-link":    "/axowiki/index.php?title=Germany&action=edit",
            "residence-link": "/axowiki/index.php?title=Germany&action=edit",
            "company-link":   "/axowiki/index.php?title=Aldi&action=edit"
        },
        {   "label":          "Gordon Moore",
            "type":           "Billionaire",
            "number":         "20",
            "ageAtPeak":      "72",
            "ageAtDeath":     "88",
            "wealth":         "26.0",
            "origin":         "San Francisco, CA",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Intel Corporation",
            "latLng":         "37.77916,-122.42009",
            "label-link":     "/axowiki/index.php?title=Gordon_Moore&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Intel_Corporation&action=edit"
        },
        {   "label":          "King Fahd",
            "type":           "Billionaire",
            "number":         "21",
            "ageAtPeak":      "75",
            "ageAtDeath":     "83",
            "wealth":         "25.0",
            "origin":         "Saudi Arabia",
            "residence":      "Saudi Arabia",
            "origin-country": "Saudi Arabia",
            "company":        "Monarch",
            "latLng":         "24.126613,45.081137",
            "label-link":     "/axowiki/index.php?title=King_Fahd&action=edit",
            "origin-link":    "/axowiki/index.php?title=Saudi_Arabia&action=edit",
            "residence-link": "/axowiki/index.php?title=Saudi_Arabia&action=edit",
            "company-link":   "/axowiki/index.php?title=Monarch&action=edit"
        },
        {   "label":          "Prince Al-Waleed bin Talal",
            "type":           "Billionaire",
            "number":         "22",
            "ageAtPeak":      "48",
            "ageAtDeath":     "48",
            "wealth":         "23.7",
            "origin":         "Saudi Arabia",
            "residence":      "Saudi Arabia",
            "origin-country": "Saudi Arabia",
            "company":        "Kingdom Holding Company",
            "latLng":         "24.126613,45.081137",
            "label-link":     "/axowiki/index.php?title=Al-Waleed_bin_Talal&action=edit",
            "origin-link":    "/axowiki/index.php?title=Saudi_Arabia&action=edit",
            "residence-link": "/axowiki/index.php?title=Saudi_Arabian&action=edit",
            "company-link":   "/axowiki/index.php?title=Kingdom_Holding_Company&action=edit"
        },
        {   "label":          "Sam Walton",
            "type":           "Billionaire",
            "number":         "23",
            "ageAtPeak":      "76",
            "ageAtDeath":     "76",
            "wealth":         "22.5",
            "origin":         "Kingfisher, OK",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Wal-Mart",
            "latLng":         "35.86036,-97.93266",
            "label-link":     "/axowiki/index.php?title=Sam_Walton&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Wal-Mart&action=edit"
        },
        {   "label":          "Bernard Arnault",
            "type":           "Billionaire",
            "number":         "24",
            "ageAtPeak":      "57",
            "ageAtDeath":     "57",
            "wealth":         "21.5",
            "origin":         "France",
            "residence":      "France",
            "origin-country": "France",
            "company":        "LVMH",
            "latLng":         "46.226699,2.209119",
            "label-link":     "/axowiki/index.php?title=Bernard_Arnault&action=edit",
            "origin-link":    "/axowiki/index.php?title=France&action=edit",
            "residence-link": "/axowiki/index.php?title=France&action=edit",
            "company-link":   "/axowiki/index.php?title=LVMH&action=edit"
        },
        {   "label":          "King Abdullah",
            "type":           "Billionaire",
            "number":         "25",
            "ageAtPeak":      "82",
            "ageAtDeath":     "82",
            "wealth":         "21.0",
            "origin":         "Saudi Arabia",
            "residence":      "Saudi Arabia",
            "origin-country": "Saudi Arabia",
            "company":        "Monarch",
            "latLng":         "24.126613,45.081137",
            "label-link":     "/axowiki/index.php?title=King_Abdullah&action=edit",
            "origin-link":    "/axowiki/index.php?title=Saudi_Arabia&action=edit",
            "residence-link": "/axowiki/index.php?title=Saudi_Arabia&action=edit",
            "company-link":   "/axowiki/index.php?title=Monarch&action=edit"
        },
        {   "label":          "Jim Walton",
            "type":           "Billionaire",
            "number":         "26",
            "ageAtPeak":      "56",
            "ageAtDeath":     "52",
            "wealth":         "20.8",
            "origin":         "Kingfisher, OK",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Wal-Mart",
            "latLng":         "35.86036,-97.93266",
            "label-link":     "/axowiki/index.php?title=Jim_Walton&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Wal-Mart&action=edit"
        },
        {   "label":          "John Walton",
            "type":           "Billionaire",
            "number":         "27",
            "ageAtPeak":      "55",
            "ageAtDeath":     "51",
            "wealth":         "20.7",
            "origin":         "Kingfisher, OK",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Wal-Mart",
            "latLng":         "35.86036,-97.93266",
            "label-link":     "/axowiki/index.php?title=John_Walton&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Wal-Mart&action=edit"
        },
        {   "label":          "Samuel Robson Walton",
            "type":           "Billionaire",
            "number":         "28",
            "ageAtPeak":      "61",
            "ageAtDeath":     "57",
            "wealth":         "20.6",
            "origin":         "Kingfisher, OK",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Wal-Mart",
            "latLng":         "35.86036,-97.93266",
            "label-link":     "/axowiki/index.php?title=Samuel_Robson_Walton&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Wal-Mart&action=edit"
        },
        {   "label":          "Alice Walton",
            "type":           "Billionaire",
            "number":         "29",
            "ageAtPeak":      "54",
            "ageAtDeath":     "50",
            "wealth":         "20.5",
            "origin":         "Kingfisher, OK",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Wal-Mart",
            "latLng":         "35.86036,-97.93266",
            "label-link":     "/axowiki/index.php?title=Alice_Walton&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Wal-Mart&action=edit"
        },
        {   "label":          "Helen Walton",
            "type":           "Billionaire",
            "number":         "30",
            "ageAtPeak":      "82",
            "ageAtDeath":     "87",
            "wealth":         "20.5",
            "origin":         "Kingfisher, OK",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Wal-Mart",
            "latLng":         "35.86036,-97.93266",
            "label-link":     "/axowiki/index.php?title=Helen_Walton&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Wal-Mart&action=edit"
        },
        {   "label":          "Sheldon Adelson",
            "type":           "Billionaire",
            "number":         "31",
            "ageAtPeak":      "72",
            "ageAtDeath":     "72",
            "wealth":         "20.5",
            "origin":         "Las Vegas, NV",
            "residence":      "United States",
            "origin-country": "United States",
            "company":        "Las Vegas Sands",
            "latLng":         "36.17188,-115.13974",
            "label-link":     "/axowiki/index.php?title=Sheldon_Adelson&action=edit",
            "origin-link":    "/axowiki/index.php?title=United_States&action=edit",
            "residence-link": "/axowiki/index.php?title=United_States&action=edit",
            "company-link":   "/axowiki/index.php?title=Las_Vegas_Sands&action=edit"
        }
    ],
    types: {
        'Billionaire': {
            pluralLabel: 'Billionaires'
        }
    },
    properties: {
        'wealth': {
            valueType:              "number"
        },
        'number': {
        	valueType:				"number"
        }
    }
}