{
    "items": [
        {   "label":      "New York City",
            "type":       "City",
            "rank":       "1",
            "latlng":     "40.71449, -74.00713",
            "state":      "New York",
            "pop":        "8214426"
        },
        {   "label":      "Los Angeles, California",
            "type":       "City",
            "rank":       "2",
            "latlng":     "34.05332, -118.24498",
            "state":      "California",
            "pop":        "3849378"
        },
        {   "label":      "Chicago",
            "type":       "City",
            "rank":       "3",
            "latlng":     "41.88414, -87.63238",
            "state":      "Illinois",
            "pop":        "2833321"
        },
        {   "label":      "Houston, Texas",
            "type":       "City",
            "rank":       "4",
            "latlng":     "29.76047, -95.36982",
            "state":      "Texas",
            "pop":        "2144491"
        },
        {   "label":      "Phoenix, Arizona",
            "type":       "City",
            "rank":       "5",
            "latlng":     "33.44793, -112.08254",
            "state":      "Arizona",
            "pop":        "1512986"
        },
        {   "label":      "Philadelphia",
            "type":       "City",
            "rank":       "6",
            "latlng":     "39.95222, -75.16237",
            "state":      "Pennsylvania",
            "pop":        "1448394"
        },
        {   "label":      "San Antonio, Texas",
            "type":       "City",
            "rank":       "7",
            "latlng":     "29.42449, -98.49463",
            "state":      "Texas",
            "pop":        "1296682"
        },
        {   "label":      "San Diego, California",
            "type":       "City",
            "rank":       "8",
            "latlng":     "32.71572, -117.16153",
            "state":      "California",
            "pop":        "1256951"
        },
        {   "label":      "Dallas, Texas",
            "type":       "City",
            "rank":       "9",
            "latlng":     "32.77805, -96.79562",
            "state":      "Texas",
            "pop":        "1232940"
        },
        {   "label":      "San Jose, California",
            "type":       "City",
            "rank":       "10",
            "latlng":     "37.35289, -121.9047",
            "state":      "California",
            "pop":        "929936"
        },
        {   "label":      "Detroit, Michigan",
            "type":       "City",
            "rank":       "11",
            "latlng":     "42.33162, -83.04779",
            "state":      "Michigan",
            "pop":        "871121"
        },
        {   "label":      "Jacksonville, Florida",
            "type":       "City",
            "rank":       "12",
            "latlng":     "30.32422, -81.65848",
            "state":      "Florida",
            "pop":        "794555"
        },
        {   "label":      "Indianapolis (balance), Indiana",
            "type":       "City",
            "rank":       "13",
            "latlng":     "39.767016, -86.156255",
            "state":      "Indiana",
            "pop":        "785597"
        },
        {   "label":      "San Francisco, California",
            "type":       "City",
            "rank":       "14",
            "latlng":     "37.77916, -122.42009",
            "state":      "California",
            "pop":        "744041"
        },
        {   "label":      "Columbus, Ohio",
            "type":       "City",
            "rank":       "15",
            "latlng":     "39.96205, -83.00302",
            "state":      "Ohio",
            "pop":        "733203"
        },
        {   "label":      "Austin, Texas",
            "type":       "City",
            "rank":       "16",
            "latlng":     "30.26757, -97.74296",
            "state":      "Texas",
            "pop":        "709893"
        },
        {   "label":      "Memphis, Tennessee",
            "type":       "City",
            "rank":       "17",
            "latlng":     "35.14962, -90.04894",
            "state":      "Tennessee",
            "pop":        "670902"
        },
        {   "label":      "Fort Worth, Texas",
            "type":       "City",
            "rank":       "18",
            "latlng":     "32.74851, -97.32923",
            "state":      "Texas",
            "pop":        "653320"
        },
        {   "label":      "Baltimore, Maryland",
            "type":       "City",
            "rank":       "19",
            "latlng":     "39.2906, -76.60962",
            "state":      "Maryland",
            "pop":        "631366"
        },
        {   "label":      "Charlotte, North Carolina",
            "type":       "City",
            "rank":       "20",
            "latlng":     "35.22246, -80.83756",
            "state":      "North Carolina",
            "pop":        "630478"
        },
        {   "label":      "El Paso, Texas",
            "type":       "City",
            "rank":       "21",
            "latlng":     "31.75916, -106.48749",
            "state":      "Texas",
            "pop":        "609415"
        },
        {   "label":      "Boston, Massachusetts",
            "type":       "City",
            "rank":       "22",
            "latlng":     "42.35864, -71.05665",
            "state":      "Massachusetts",
            "pop":        "590763"
        },
        {   "label":      "Seattle, Washington",
            "type":       "City",
            "rank":       "23",
            "latlng":     "47.60342, -122.32971",
            "state":      "Washington",
            "pop":        "582454"
        },
        {   "label":      "Washington, District of Columbia",
            "type":       "City",
            "rank":       "24",
            "latlng":     "38.88951, -77.032",
            "state":      "District of Columbia",
            "pop":        "581530"
        },
        {   "label":      "Milwaukee, Wisconsin",
            "type":       "City",
            "rank":       "25",
            "latlng":     "43.04178, -87.90685",
            "state":      "Wisconsin",
            "pop":        "573358"
        },
        {   "label":      "Denver, Colorado",
            "type":       "City",
            "rank":       "26",
            "latlng":     "39.74004, -104.99227",
            "state":      "Colorado",
            "pop":        "566974"
        },
        {   "label":      "Louisville-Jefferson County (balance), Kentucky",
            "type":       "City",
            "rank":       "27",
            "latlng":     "38.25409, -85.75908",
            "state":      "Kentucky",
            "pop":        "554496"
        },
        {   "label":      "Las Vegas, Nevada",
            "type":       "City",
            "rank":       "28",
            "latlng":     "36.17188, -115.13974",
            "state":      "Nevada",
            "pop":        "552539"
        },
        {   "label":      "Nashville-Davidson (balance), Tennessee",
            "type":       "City",
            "rank":       "29",
            "latlng":     "36.15888, -86.782097",
            "state":      "Tennessee",
            "pop":        "552120"
        },
        {   "label":      "Oklahoma City, Oklahoma",
            "type":       "City",
            "rank":       "30",
            "latlng":     "35.47205, -97.52032",
            "state":      "Oklahoma",
            "pop":        "537734"
        },
        {   "label":      "Portland, Oregon",
            "type":       "City",
            "rank":       "31",
            "latlng":     "45.51181, -122.67568",
            "state":      "Oregon",
            "pop":        "537081"
        },
        {   "label":      "Tucson, Arizona",
            "type":       "City",
            "rank":       "32",
            "latlng":     "32.22154, -110.96979",
            "state":      "Arizona",
            "pop":        "518956"
        },
        {   "label":      "Albuquerque, New Mexico",
            "type":       "City",
            "rank":       "33",
            "latlng":     "35.0841, -106.64863",
            "state":      "New Mexico",
            "pop":        "504949"
        },
        {   "label":      "Atlanta, Georgia",
            "type":       "City",
            "rank":       "34",
            "latlng":     "33.74813, -84.39087",
            "state":      "Georgia",
            "pop":        "486411"
        },
        {   "label":      "Long Beach, California",
            "type":       "City",
            "rank":       "35",
            "latlng":     "33.7664, -118.19235",
            "state":      "California",
            "pop":        "472494"
        },
        {   "label":      "Fresno, California",
            "type":       "City",
            "rank":       "36",
            "latlng":     "36.74021, -119.78615",
            "state":      "California",
            "pop":        "466714"
        },
        {   "label":      "Sacramento, California",
            "type":       "City",
            "rank":       "37",
            "latlng":     "38.57905, -121.49096",
            "state":      "California",
            "pop":        "453781"
        },
        {   "label":      "Mesa, Arizona",
            "type":       "City",
            "rank":       "38",
            "latlng":     "33.41704, -111.83142",
            "state":      "Arizona",
            "pop":        "447541"
        },
        {   "label":      "Kansas City, Missouri",
            "type":       "City",
            "rank":       "39",
            "latlng":     "39.10295, -94.58302",
            "state":      "Missouri",
            "pop":        "447306"
        },
        {   "label":      "Cleveland, Ohio",
            "type":       "City",
            "rank":       "40",
            "latlng":     "41.50434, -81.6905",
            "state":      "Ohio",
            "pop":        "444313"
        },
        {   "label":      "Virginia Beach, Virginia",
            "type":       "City",
            "rank":       "41",
            "latlng":     "36.75503, -76.0592",
            "state":      "Virginia",
            "pop":        "435619"
        },
        {   "label":      "Omaha, Nebraska",
            "type":       "City",
            "rank":       "42",
            "latlng":     "41.2607, -95.93989",
            "state":      "Nebraska",
            "pop":        "419545"
        },
        {   "label":      "Miami, Florida",
            "type":       "City",
            "rank":       "43",
            "latlng":     "25.72898, -80.23745",
            "state":      "Florida",
            "pop":        "404048"
        },
        {   "label":      "Oakland, California",
            "type":       "City",
            "rank":       "44",
            "latlng":     "37.80501, -122.27303",
            "state":      "California",
            "pop":        "397067"
        },
        {   "label":      "Tulsa, Oklahoma",
            "type":       "City",
            "rank":       "45",
            "latlng":     "36.14976, -95.99331",
            "state":      "Oklahoma",
            "pop":        "382872"
        },
        {   "label":      "Honolulu, Hawaii",
            "type":       "City",
            "rank":       "46",
            "latlng":     "21.30473, -157.85762",
            "state":      "Hawaii",
            "pop":        "377357"
        },
        {   "label":      "Minneapolis, Minnesota",
            "type":       "City",
            "rank":       "47",
            "latlng":     "44.9785, -93.26529",
            "state":      "Minnesota",
            "pop":        "372833"
        },
        {   "label":      "Colorado Springs, Colorado",
            "type":       "City",
            "rank":       "48",
            "latlng":     "38.83311, -104.82177",
            "state":      "Colorado",
            "pop":        "372437"
        },
        {   "label":      "Arlington, Texas",
            "type":       "City",
            "rank":       "49",
            "latlng":     "32.73565, -97.10772",
            "state":      "Texas",
            "pop":        "367197"
        },
        {   "label":      "Wichita, Kansas",
            "type":       "City",
            "rank":       "50",
            "latlng":     "37.68697, -97.33558",
            "state":      "Kansas",
            "pop":        "357698"
        },
        {   "label":      "Raleigh, North Carolina",
            "type":       "City",
            "rank":       "51",
            "latlng":     "35.78552, -78.64263",
            "state":      "North Carolina",
            "pop":        "356321"
        },
        {   "label":      "St. Louis, Missouri",
            "type":       "City",
            "rank":       "52",
            "latlng":     "38.62756, -90.19896",
            "state":      "Missouri",
            "pop":        "353837"
        },
        {   "label":      "Santa Ana, California",
            "type":       "City",
            "rank":       "53",
            "latlng":     "33.74813, -117.87446",
            "state":      "California",
            "pop":        "340024"
        },
        {   "label":      "Anaheim, California",
            "type":       "City",
            "rank":       "54",
            "latlng":     "33.8327, -117.91572",
            "state":      "California",
            "pop":        "334425"
        },
        {   "label":      "Tampa, Florida",
            "type":       "City",
            "rank":       "55",
            "latlng":     "27.9465, -82.45929",
            "state":      "Florida",
            "pop":        "332888"
        },
        {   "label":      "Cincinnati, Ohio",
            "type":       "City",
            "rank":       "56",
            "latlng":     "39.10647, -84.50477",
            "state":      "Ohio",
            "pop":        "332252"
        },
        {   "label":      "Pittsburgh, Pennsylvania",
            "type":       "City",
            "rank":       "57",
            "latlng":     "40.43837, -79.99755",
            "state":      "Pennsylvania",
            "pop":        "312819"
        },
        {   "label":      "Bakersfield, California",
            "type":       "City",
            "rank":       "58",
            "latlng":     "35.36697, -119.01889",
            "state":      "California",
            "pop":        "308392"
        },
        {   "label":      "Aurora, Colorado",
            "type":       "City",
            "rank":       "59",
            "latlng":     "39.69107, -104.86592",
            "state":      "Colorado",
            "pop":        "303582"
        },
        {   "label":      "Toledo, Ohio",
            "type":       "City",
            "rank":       "60",
            "latlng":     "41.65378, -83.53613",
            "state":      "Ohio",
            "pop":        "298446"
        },
        {   "label":      "Riverside, California",
            "type":       "City",
            "rank":       "61",
            "latlng":     "33.98166, -117.37385",
            "state":      "California",
            "pop":        "293761"
        },
        {   "label":      "Stockton, California",
            "type":       "City",
            "rank":       "62",
            "latlng":     "37.95357, -121.29072",
            "state":      "California",
            "pop":        "290141"
        },
        {   "label":      "Corpus Christi, Texas",
            "type":       "City",
            "rank":       "63",
            "latlng":     "27.79629, -97.40355",
            "state":      "Texas",
            "pop":        "285267"
        },
        {   "label":      "Newark, New Jersey",
            "type":       "City",
            "rank":       "64",
            "latlng":     "40.73194, -74.17415",
            "state":      "New Jersey",
            "pop":        "281402"
        },
        {   "label":      "Anchorage, Alaska",
            "type":       "City",
            "rank":       "65",
            "latlng":     "61.21756, -149.85775",
            "state":      "Alaska",
            "pop":        "278700"
        },
        {   "label":      "Buffalo, New York",
            "type":       "City",
            "rank":       "66",
            "latlng":     "42.88539, -78.87838",
            "state":      "New York",
            "pop":        "276059"
        },
        {   "label":      "St. Paul, Minnesota",
            "type":       "City",
            "rank":       "67",
            "latlng":     "44.94397, -93.093",
            "state":      "Minnesota",
            "pop":        "273535"
        },
        {   "label":      "Lexington-Fayette, Kentucky",
            "type":       "City",
            "rank":       "68",
            "latlng":     "38.048906, -84.499838",
            "state":      "Kentucky",
            "pop":        "270789"
        },
        {   "label":      "Plano, Texas",
            "type":       "City",
            "rank":       "69",
            "latlng":     "33.02078, -96.69917",
            "state":      "Texas",
            "pop":        "255009"
        },
        {   "label":      "Fort Wayne, Indiana",
            "type":       "City",
            "rank":       "70",
            "latlng":     "41.07552, -85.09906",
            "state":      "Indiana",
            "pop":        "248637"
        },
        {   "label":      "St. Petersburg, Florida",
            "type":       "City",
            "rank":       "71",
            "latlng":     "27.77113, -82.63933",
            "state":      "Florida",
            "pop":        "248098"
        },
        {   "label":      "Glendale, Arizona",
            "type":       "City",
            "rank":       "72",
            "latlng":     "33.53861, -112.18576",
            "state":      "Arizona",
            "pop":        "246531"
        },
        {   "label":      "Jersey City, New Jersey",
            "type":       "City",
            "rank":       "73",
            "latlng":     "40.71745, -74.04323",
            "state":      "New Jersey",
            "pop":        "241789"
        },
        {   "label":      "Lincoln, Nebraska",
            "type":       "City",
            "rank":       "74",
            "latlng":     "40.81356, -96.70773",
            "state":      "Nebraska",
            "pop":        "241167"
        },
        {   "label":      "Henderson, Nevada",
            "type":       "City",
            "rank":       "75",
            "latlng":     "36.03079, -114.98112",
            "state":      "Nevada",
            "pop":        "240614"
        },
        {   "label":      "Chandler, Arizona",
            "type":       "City",
            "rank":       "76",
            "latlng":     "33.30287, -111.84081",
            "state":      "Arizona",
            "pop":        "240595"
        },
        {   "label":      "Greensboro, North Carolina",
            "type":       "City",
            "rank":       "77",
            "latlng":     "36.06903, -79.79468",
            "state":      "North Carolina",
            "pop":        "236865"
        },
        {   "label":      "Scottsdale, Arizona",
            "type":       "City",
            "rank":       "78",
            "latlng":     "33.49396, -111.92141",
            "state":      "Arizona",
            "pop":        "231127"
        },
        {   "label":      "Baton Rouge, Louisiana",
            "type":       "City",
            "rank":       "79",
            "latlng":     "30.44346, -91.18689",
            "state":      "Louisiana",
            "pop":        "229553"
        },
        {   "label":      "Birmingham, Alabama",
            "type":       "City",
            "rank":       "80",
            "latlng":     "33.52028, -86.81151",
            "state":      "Alabama",
            "pop":        "229424"
        },
        {   "label":      "Norfolk, Virginia",
            "type":       "City",
            "rank":       "81",
            "latlng":     "36.8468, -76.28507",
            "state":      "Virginia",
            "pop":        "229112"
        },
        {   "label":      "Madison, Wisconsin",
            "type":       "City",
            "rank":       "82",
            "latlng":     "43.07292, -89.38667",
            "state":      "Wisconsin",
            "pop":        "223389"
        },
        {   "label":      "New Orleans, Louisiana",
            "type":       "City",
            "rank":       "83",
            "latlng":     "30.03451, -90.024788",
            "state":      "Louisiana",
            "pop":        "223388"
        },
        {   "label":      "Chesapeake, Virginia",
            "type":       "City",
            "rank":       "84",
            "latlng":     "36.71434, -76.24785",
            "state":      "Virginia",
            "pop":        "220560"
        },
        {   "label":      "Orlando, Florida",
            "type":       "City",
            "rank":       "85",
            "latlng":     "28.53773, -81.37739",
            "state":      "Florida",
            "pop":        "220186"
        },
        {   "label":      "Garland, Texas",
            "type":       "City",
            "rank":       "86",
            "latlng":     "32.91386, -96.63652",
            "state":      "Texas",
            "pop":        "217963"
        },
        {   "label":      "Hialeah, Florida",
            "type":       "City",
            "rank":       "87",
            "latlng":     "25.82674, -80.28145",
            "state":      "Florida",
            "pop":        "217141"
        },
        {   "label":      "Laredo, Texas",
            "type":       "City",
            "rank":       "88",
            "latlng":     "27.53092, -99.502",
            "state":      "Texas",
            "pop":        "215484"
        },
        {   "label":      "Chula Vista, California",
            "type":       "City",
            "rank":       "89",
            "latlng":     "32.64055, -117.08419",
            "state":      "California",
            "pop":        "212756"
        },
        {   "label":      "Lubbock, Texas",
            "type":       "City",
            "rank":       "90",
            "latlng":     "33.59245, -101.85587",
            "state":      "Texas",
            "pop":        "212169"
        },
        {   "label":      "Reno, Nevada",
            "type":       "City",
            "rank":       "91",
            "latlng":     "39.5245, -119.81164",
            "state":      "Nevada",
            "pop":        "210255"
        },
        {   "label":      "Akron, Ohio",
            "type":       "City",
            "rank":       "92",
            "latlng":     "41.08414, -81.51407",
            "state":      "Ohio",
            "pop":        "209704"
        },
        {   "label":      "Durham, North Carolina",
            "type":       "City",
            "rank":       "93",
            "latlng":     "35.99522, -78.89601",
            "state":      "North Carolina",
            "pop":        "209009"
        },
        {   "label":      "Rochester, New York",
            "type":       "City",
            "rank":       "94",
            "latlng":     "43.15549, -77.61601",
            "state":      "New York",
            "pop":        "208123"
        },
        {   "label":      "Modesto, California",
            "type":       "City",
            "rank":       "95",
            "latlng":     "37.6383, -120.99959",
            "state":      "California",
            "pop":        "205721"
        },
        {   "label":      "Montgomery, Alabama",
            "type":       "City",
            "rank":       "96",
            "latlng":     "32.38012, -86.30063",
            "state":      "Alabama",
            "pop":        "201998"
        },
        {   "label":      "Fremont, California",
            "type":       "City",
            "rank":       "97",
            "latlng":     "37.55096, -121.98214",
            "state":      "California",
            "pop":        "201691"
        },
        {   "label":      "Shreveport, Louisiana",
            "type":       "City",
            "rank":       "98",
            "latlng":     "32.51461, -93.74728",
            "state":      "Louisiana",
            "pop":        "200199"
        },
        {   "label":      "Arlington, Virginia",
            "type":       "City",
            "rank":       "99",
            "latlng":     "38.89046, -77.08629",
            "state":      "Virginia",
            "pop":        "199776"
        },
        {   "label":      "Glendale, California",
            "type":       "City",
            "rank":       "100",
            "latlng":     "34.14636, -118.24801",
            "state":      "California",
            "pop":        "199463"
        },
        {   "label":      "San Bernardino, California",
            "type":       "City",
            "rank":       "101",
            "latlng":     "34.10524, -117.29416",
            "state":      "California",
            "pop":        "198985"
        },
        {   "label":      "Boise, Idaho",
            "type":       "City",
            "rank":       "102",
            "latlng":     "43.60698, -116.19337",
            "state":      "Idaho",
            "pop":        "198638"
        },
        {   "label":      "Spokane, Washington",
            "type":       "City",
            "rank":       "103",
            "latlng":     "47.65728, -117.41228",
            "state":      "Washington",
            "pop":        "198081"
        },
        {   "label":      "Yonkers, New York",
            "type":       "City",
            "rank":       "104",
            "latlng":     "40.93251, -73.89889",
            "state":      "New York",
            "pop":        "197852"
        },
        {   "label":      "North Las Vegas, Nevada",
            "type":       "City",
            "rank":       "105",
            "latlng":     "36.19897, -115.1185",
            "state":      "Nevada",
            "pop":        "197567"
        },
        {   "label":      "Winston-Salem, North Carolina",
            "type":       "City",
            "rank":       "106",
            "latlng":     "36.0996, -80.24105",
            "state":      "North Carolina",
            "pop":        "196990"
        },
        {   "label":      "Tacoma, Washington",
            "type":       "City",
            "rank":       "107",
            "latlng":     "47.2551, -122.44166",
            "state":      "Washington",
            "pop":        "196532"
        },
        {   "label":      "Irving, Texas",
            "type":       "City",
            "rank":       "108",
            "latlng":     "32.81355, -96.95579",
            "state":      "Texas",
            "pop":        "196084"
        },
        {   "label":      "Huntington Beach, California",
            "type":       "City",
            "rank":       "109",
            "latlng":     "33.67747, -118.0015",
            "state":      "California",
            "pop":        "194436"
        },
        {   "label":      "Irvine, California",
            "type":       "City",
            "rank":       "110",
            "latlng":     "33.68684, -117.82537",
            "state":      "California",
            "pop":        "193956"
        },
        {   "label":      "Des Moines, Iowa",
            "type":       "City",
            "rank":       "111",
            "latlng":     "41.58978, -93.61569",
            "state":      "Iowa",
            "pop":        "193886"
        },
        {   "label":      "Grand Rapids, Michigan",
            "type":       "City",
            "rank":       "112",
            "latlng":     "42.96635, -85.67118",
            "state":      "Michigan",
            "pop":        "193083"
        },
        {   "label":      "Richmond, Virginia",
            "type":       "City",
            "rank":       "113",
            "latlng":     "37.54057, -77.43341",
            "state":      "Virginia",
            "pop":        "192913"
        },
        {   "label":      "Mobile, Alabama",
            "type":       "City",
            "rank":       "114",
            "latlng":     "30.68639, -88.05325",
            "state":      "Alabama",
            "pop":        "192830"
        },
        {   "label":      "Gilbert, Arizona",
            "type":       "City",
            "rank":       "115",
            "latlng":     "33.32902, -111.78972",
            "state":      "Arizona",
            "pop":        "191517"
        },
        {   "label":      "Augusta-Richmond County (balance), Georgia",
            "type":       "City",
            "rank":       "116",
            "latlng":     "33.478532, -81.975524",
            "state":      "Georgia",
            "pop":        "189366"
        },
        {   "label":      "Columbus, Georgia",
            "type":       "City",
            "rank":       "117",
            "latlng":     "32.46292, -84.98763",
            "state":      "Georgia",
            "pop":        "188660"
        },
        {   "label":      "Fort Lauderdale, Florida",
            "type":       "City",
            "rank":       "118",
            "latlng":     "26.12276, -80.15047",
            "state":      "Florida",
            "pop":        "185804"
        },
        {   "label":      "Amarillo, Texas",
            "type":       "City",
            "rank":       "119",
            "latlng":     "35.20725, -101.83389",
            "state":      "Texas",
            "pop":        "185525"
        },
        {   "label":      "Oxnard, California",
            "type":       "City",
            "rank":       "120",
            "latlng":     "34.20039, -119.18044",
            "state":      "California",
            "pop":        "184463"
        },
        {   "label":      "Little Rock, Arkansas",
            "type":       "City",
            "rank":       "121",
            "latlng":     "34.74865, -92.27448",
            "state":      "Arkansas",
            "pop":        "184422"
        },
        {   "label":      "Moreno Valley, California",
            "type":       "City",
            "rank":       "122",
            "latlng":     "33.91657, -117.26118",
            "state":      "California",
            "pop":        "183571"
        },
        {   "label":      "Knoxville, Tennessee",
            "type":       "City",
            "rank":       "123",
            "latlng":     "35.96054, -83.92079",
            "state":      "Tennessee",
            "pop":        "182337"
        },
        {   "label":      "Salt Lake City, Utah",
            "type":       "City",
            "rank":       "124",
            "latlng":     "40.75952, -111.88818",
            "state":      "Utah",
            "pop":        "178858"
        },
        {   "label":      "Newport News, Virginia",
            "type":       "City",
            "rank":       "125",
            "latlng":     "36.98047, -76.42945",
            "state":      "Virginia",
            "pop":        "178281"
        },
        {   "label":      "Jackson, Mississippi",
            "type":       "City",
            "rank":       "126",
            "latlng":     "32.29868, -90.18054",
            "state":      "Mississippi",
            "pop":        "176614"
        },
        {   "label":      "Worcester, Massachusetts",
            "type":       "City",
            "rank":       "127",
            "latlng":     "42.26298, -71.80232",
            "state":      "Massachusetts",
            "pop":        "175454"
        },
        {   "label":      "Providence, Rhode Island",
            "type":       "City",
            "rank":       "128",
            "latlng":     "41.82383, -71.41202",
            "state":      "Rhode Island",
            "pop":        "175255"
        },
        {   "label":      "Ontario, California",
            "type":       "City",
            "rank":       "129",
            "latlng":     "34.06462, -117.64781",
            "state":      "California",
            "pop":        "173351"
        },
        {   "label":      "Brownsville, Texas",
            "type":       "City",
            "rank":       "130",
            "latlng":     "25.89958, -97.49553",
            "state":      "Texas",
            "pop":        "172437"
        },
        {   "label":      "Rancho Cucamonga, California",
            "type":       "City",
            "rank":       "131",
            "latlng":     "34.10265, -117.57381",
            "state":      "California",
            "pop":        "170714"
        },
        {   "label":      "Aurora, Illinois",
            "type":       "City",
            "rank":       "132",
            "latlng":     "41.757, -88.31575",
            "state":      "Illinois",
            "pop":        "170617"
        },
        {   "label":      "Fontana, California",
            "type":       "City",
            "rank":       "133",
            "latlng":     "34.10205, -117.43572",
            "state":      "California",
            "pop":        "170099"
        },
        {   "label":      "Tempe, Arizona",
            "type":       "City",
            "rank":       "134",
            "latlng":     "33.42545, -111.9383",
            "state":      "Arizona",
            "pop":        "169712"
        },
        {   "label":      "Huntsville, Alabama",
            "type":       "City",
            "rank":       "135",
            "latlng":     "34.72911, -86.58495",
            "state":      "Alabama",
            "pop":        "168132"
        },
        {   "label":      "Fayetteville, North Carolina",
            "type":       "City",
            "rank":       "136",
            "latlng":     "35.05449, -78.87759",
            "state":      "North Carolina",
            "pop":        "168033"
        },
        {   "label":      "Santa Clarita, California",
            "type":       "City",
            "rank":       "137",
            "latlng":     "34.4134, -118.55187",
            "state":      "California",
            "pop":        "168008"
        },
        {   "label":      "Overland Park, Kansas",
            "type":       "City",
            "rank":       "138",
            "latlng":     "38.98489, -94.67169",
            "state":      "Kansas",
            "pop":        "166722"
        },
        {   "label":      "Garden Grove, California",
            "type":       "City",
            "rank":       "139",
            "latlng":     "33.77602, -117.9368",
            "state":      "California",
            "pop":        "166296"
        },
        {   "label":      "Oceanside, California",
            "type":       "City",
            "rank":       "140",
            "latlng":     "33.19717, -117.38055",
            "state":      "California",
            "pop":        "165803"
        },
        {   "label":      "Tallahassee, Florida",
            "type":       "City",
            "rank":       "141",
            "latlng":     "30.43978, -84.28065",
            "state":      "Florida",
            "pop":        "159012"
        },
        {   "label":      "Vancouver, Washington",
            "type":       "City",
            "rank":       "142",
            "latlng":     "45.63221, -122.67155",
            "state":      "Washington",
            "pop":        "158855"
        },
        {   "label":      "Dayton, Ohio",
            "type":       "City",
            "rank":       "143",
            "latlng":     "39.7591, -84.19446",
            "state":      "Ohio",
            "pop":        "156771"
        },
        {   "label":      "Chattanooga, Tennessee",
            "type":       "City",
            "rank":       "144",
            "latlng":     "35.04642, -85.30942",
            "state":      "Tennessee",
            "pop":        "155190"
        },
        {   "label":      "Rockford, Illinois",
            "type":       "City",
            "rank":       "145",
            "latlng":     "42.2669, -89.07836",
            "state":      "Illinois",
            "pop":        "155138"
        },
        {   "label":      "Pomona, California",
            "type":       "City",
            "rank":       "146",
            "latlng":     "34.05464, -117.75006",
            "state":      "California",
            "pop":        "154271"
        },
        {   "label":      "Santa Rosa, California",
            "type":       "City",
            "rank":       "147",
            "latlng":     "38.43772, -122.71238",
            "state":      "California",
            "pop":        "154212"
        },
        {   "label":      "Grand Prairie, Texas",
            "type":       "City",
            "rank":       "148",
            "latlng":     "32.74765, -97.0072",
            "state":      "Texas",
            "pop":        "153812"
        },
        {   "label":      "Salem, Oregon",
            "type":       "City",
            "rank":       "149",
            "latlng":     "44.93319, -123.04309",
            "state":      "Oregon",
            "pop":        "152239"
        },
        {   "label":      "Cape Coral, Florida",
            "type":       "City",
            "rank":       "150",
            "latlng":     "26.62974, -81.9574",
            "state":      "Florida",
            "pop":        "151389"
        },
        {   "label":      "Springfield, Massachusetts",
            "type":       "City",
            "rank":       "151",
            "latlng":     "42.10126, -72.5893",
            "state":      "Massachusetts",
            "pop":        "151176"
        },
        {   "label":      "Springfield, Missouri",
            "type":       "City",
            "rank":       "152",
            "latlng":     "37.20902, -93.29156",
            "state":      "Missouri",
            "pop":        "150797"
        },
        {   "label":      "Corona, California",
            "type":       "City",
            "rank":       "153",
            "latlng":     "33.87789, -117.57501",
            "state":      "California",
            "pop":        "150253"
        },
        {   "label":      "Pembroke Pines, Florida",
            "type":       "City",
            "rank":       "154",
            "latlng":     "26.00804, -80.28086",
            "state":      "Florida",
            "pop":        "150064"
        },
        {   "label":      "Paterson, New Jersey",
            "type":       "City",
            "rank":       "155",
            "latlng":     "40.91903, -74.1711",
            "state":      "New Jersey",
            "pop":        "148708"
        },
        {   "label":      "Eugene, Oregon",
            "type":       "City",
            "rank":       "156",
            "latlng":     "44.04985, -123.08892",
            "state":      "Oregon",
            "pop":        "146356"
        },
        {   "label":      "Hollywood, Florida",
            "type":       "City",
            "rank":       "157",
            "latlng":     "26.01043, -80.16005",
            "state":      "Florida",
            "pop":        "145794"
        },
        {   "label":      "Salinas, California",
            "type":       "City",
            "rank":       "158",
            "latlng":     "36.67085, -121.65488",
            "state":      "California",
            "pop":        "145032"
        },
        {   "label":      "Hampton, Virginia",
            "type":       "City",
            "rank":       "159",
            "latlng":     "37.02784, -76.34512",
            "state":      "Virginia",
            "pop":        "145017"
        },
        {   "label":      "Pasadena, Texas",
            "type":       "City",
            "rank":       "160",
            "latlng":     "29.6909, -95.19632",
            "state":      "Texas",
            "pop":        "144793"
        },
        {   "label":      "Pasadena, California",
            "type":       "City",
            "rank":       "161",
            "latlng":     "34.14723, -118.14422",
            "state":      "California",
            "pop":        "144133"
        },
        {   "label":      "Port St. Lucie, Florida",
            "type":       "City",
            "rank":       "162",
            "latlng":     "27.27417, -80.36336",
            "state":      "Florida",
            "pop":        "143868"
        },
        {   "label":      "Kansas City, Kansas",
            "type":       "City",
            "rank":       "163",
            "latlng":     "39.10295, -94.58302",
            "state":      "Kansas",
            "pop":        "143801"
        },
        {   "label":      "Naperville, Illinois",
            "type":       "City",
            "rank":       "164",
            "latlng":     "41.7705, -88.153",
            "state":      "Illinois",
            "pop":        "142901"
        },
        {   "label":      "Joliet, Illinois",
            "type":       "City",
            "rank":       "165",
            "latlng":     "41.52485, -88.08507",
            "state":      "Illinois",
            "pop":        "142702"
        },
        {   "label":      "Sioux Falls, South Dakota",
            "type":       "City",
            "rank":       "166",
            "latlng":     "43.54534, -96.73129",
            "state":      "South Dakota",
            "pop":        "142396"
        },
        {   "label":      "Torrance, California",
            "type":       "City",
            "rank":       "167",
            "latlng":     "33.83664, -118.34141",
            "state":      "California",
            "pop":        "142350"
        },
        {   "label":      "Peoria, Arizona",
            "type":       "City",
            "rank":       "168",
            "latlng":     "33.57726, -112.24092",
            "state":      "Arizona",
            "pop":        "142024"
        },
        {   "label":      "Lancaster, California",
            "type":       "City",
            "rank":       "169",
            "latlng":     "34.6989, -118.14481",
            "state":      "California",
            "pop":        "140804"
        },
        {   "label":      "Syracuse, New York",
            "type":       "City",
            "rank":       "170",
            "latlng":     "43.04999, -76.14739",
            "state":      "New York",
            "pop":        "140658"
        },
        {   "label":      "Hayward, California",
            "type":       "City",
            "rank":       "171",
            "latlng":     "37.67119, -122.08614",
            "state":      "California",
            "pop":        "140606"
        },
        {   "label":      "Lakewood, Colorado",
            "type":       "City",
            "rank":       "172",
            "latlng":     "39.71095, -105.08276",
            "state":      "Colorado",
            "pop":        "140024"
        },
        {   "label":      "Palmdale, California",
            "type":       "City",
            "rank":       "173",
            "latlng":     "34.57848, -118.11641",
            "state":      "California",
            "pop":        "138790"
        },
        {   "label":      "Bridgeport, Connecticut",
            "type":       "City",
            "rank":       "174",
            "latlng":     "41.18193, -73.19129",
            "state":      "Connecticut",
            "pop":        "137912"
        },
        {   "label":      "Alexandria, Virginia",
            "type":       "City",
            "rank":       "175",
            "latlng":     "38.80461, -77.04308",
            "state":      "Virginia",
            "pop":        "136974"
        },
        {   "label":      "Orange, California",
            "type":       "City",
            "rank":       "176",
            "latlng":     "33.78781, -117.85039",
            "state":      "California",
            "pop":        "135070"
        },
        {   "label":      "Warren, Michigan",
            "type":       "City",
            "rank":       "177",
            "latlng":     "42.51111, -83.02848",
            "state":      "Michigan",
            "pop":        "134589"
        },
        {   "label":      "Escondido, California",
            "type":       "City",
            "rank":       "178",
            "latlng":     "33.12315, -117.08221",
            "state":      "California",
            "pop":        "133510"
        },
        {   "label":      "Fullerton, California",
            "type":       "City",
            "rank":       "179",
            "latlng":     "33.87037, -117.92912",
            "state":      "California",
            "pop":        "132918"
        },
        {   "label":      "Mesquite, Texas",
            "type":       "City",
            "rank":       "180",
            "latlng":     "32.78301, -96.60169",
            "state":      "Texas",
            "pop":        "131447"
        },
        {   "label":      "Sunnyvale, California",
            "type":       "City",
            "rank":       "181",
            "latlng":     "37.37155, -122.03825",
            "state":      "California",
            "pop":        "130519"
        },
        {   "label":      "Coral Springs, Florida",
            "type":       "City",
            "rank":       "182",
            "latlng":     "26.27254, -80.25305",
            "state":      "Florida",
            "pop":        "129805"
        },
        {   "label":      "Fort Collins, Colorado",
            "type":       "City",
            "rank":       "183",
            "latlng":     "40.58149, -105.07627",
            "state":      "Colorado",
            "pop":        "129467"
        },
        {   "label":      "Elk Grove, California",
            "type":       "City",
            "rank":       "184",
            "latlng":     "38.40904, -121.37381",
            "state":      "California",
            "pop":        "129184"
        },
        {   "label":      "Sterling Heights, Michigan",
            "type":       "City",
            "rank":       "185",
            "latlng":     "42.59325, -83.01338",
            "state":      "Michigan",
            "pop":        "127991"
        },
        {   "label":      "Savannah, Georgia",
            "type":       "City",
            "rank":       "186",
            "latlng":     "32.08078, -81.09072",
            "state":      "Georgia",
            "pop":        "127889"
        },
        {   "label":      "McAllen, Texas",
            "type":       "City",
            "rank":       "187",
            "latlng":     "26.20741, -98.22935",
            "state":      "Texas",
            "pop":        "126411"
        },
        {   "label":      "Elizabeth, New Jersey",
            "type":       "City",
            "rank":       "188",
            "latlng":     "40.66351, -74.21151",
            "state":      "New Jersey",
            "pop":        "126179"
        },
        {   "label":      "Hartford, Connecticut",
            "type":       "City",
            "rank":       "189",
            "latlng":     "41.76331, -72.67403",
            "state":      "Connecticut",
            "pop":        "124512"
        },
        {   "label":      "Cedar Rapids, Iowa",
            "type":       "City",
            "rank":       "190",
            "latlng":     "41.97634, -91.67377",
            "state":      "Iowa",
            "pop":        "124417"
        },
        {   "label":      "Thousand Oaks, California",
            "type":       "City",
            "rank":       "191",
            "latlng":     "34.18505, -118.89429",
            "state":      "California",
            "pop":        "124207"
        },
        {   "label":      "New Haven, Connecticut",
            "type":       "City",
            "rank":       "192",
            "latlng":     "41.3132, -72.92195",
            "state":      "Connecticut",
            "pop":        "124001"
        },
        {   "label":      "El Monte, California",
            "type":       "City",
            "rank":       "193",
            "latlng":     "34.07067, -118.03033",
            "state":      "California",
            "pop":        "123162"
        },
        {   "label":      "Concord, California",
            "type":       "City",
            "rank":       "194",
            "latlng":     "37.98083, -122.02516",
            "state":      "California",
            "pop":        "122204"
        },
        {   "label":      "Topeka, Kansas",
            "type":       "City",
            "rank":       "195",
            "latlng":     "39.05673, -95.67749",
            "state":      "Kansas",
            "pop":        "122113"
        },
        {   "label":      "Carrollton, Texas",
            "type":       "City",
            "rank":       "196",
            "latlng":     "32.9756, -96.89023",
            "state":      "Texas",
            "pop":        "121604"
        },
        {   "label":      "Waco, Texas",
            "type":       "City",
            "rank":       "197",
            "latlng":     "31.57169, -97.14974",
            "state":      "Texas",
            "pop":        "121496"
        },
        {   "label":      "Simi Valley, California",
            "type":       "City",
            "rank":       "198",
            "latlng":     "34.28894, -118.71772",
            "state":      "California",
            "pop":        "121288"
        },
        {   "label":      "Columbia, South Carolina",
            "type":       "City",
            "rank":       "199",
            "latlng":     "33.99856, -81.04521",
            "state":      "South Carolina",
            "pop":        "119961"
        },
        {   "label":      "West Valley, Utah",
            "type":       "City",
            "rank":       "200",
            "latlng":     "40.696661, -111.980622",
            "state":      "Utah",
            "pop":        "119841"
        },
        {   "label":      "Stamford, Connecticut",
            "type":       "City",
            "rank":       "201",
            "latlng":     "41.05164, -73.54225",
            "state":      "Connecticut",
            "pop":        "119261"
        },
        {   "label":      "Bellevue, Washington",
            "type":       "City",
            "rank":       "202",
            "latlng":     "47.60995, -122.18686",
            "state":      "Washington",
            "pop":        "118186"
        },
        {   "label":      "Flint, Michigan",
            "type":       "City",
            "rank":       "203",
            "latlng":     "43.01077, -83.68599",
            "state":      "Michigan",
            "pop":        "117068"
        },
        {   "label":      "Vallejo, California",
            "type":       "City",
            "rank":       "204",
            "latlng":     "38.10083, -122.25497",
            "state":      "California",
            "pop":        "116844"
        },
        {   "label":      "Springfield, Illinois",
            "type":       "City",
            "rank":       "205",
            "latlng":     "39.80105, -89.64361",
            "state":      "Illinois",
            "pop":        "116482"
        },
        {   "label":      "Evansville, Indiana",
            "type":       "City",
            "rank":       "206",
            "latlng":     "37.9769, -87.56413",
            "state":      "Indiana",
            "pop":        "115738"
        },
        {   "label":      "Inglewood, California",
            "type":       "City",
            "rank":       "207",
            "latlng":     "33.96183, -118.35623",
            "state":      "California",
            "pop":        "114914"
        },
        {   "label":      "Abilene, Texas",
            "type":       "City",
            "rank":       "208",
            "latlng":     "32.44917, -99.74142",
            "state":      "Texas",
            "pop":        "114797"
        },
        {   "label":      "Olathe, Kansas",
            "type":       "City",
            "rank":       "209",
            "latlng":     "38.88358, -94.82003",
            "state":      "Kansas",
            "pop":        "114662"
        },
        {   "label":      "Lansing, Michigan",
            "type":       "City",
            "rank":       "210",
            "latlng":     "42.73202, -84.55224",
            "state":      "Michigan",
            "pop":        "114276"
        },
        {   "label":      "Lafayette, Louisiana",
            "type":       "City",
            "rank":       "211",
            "latlng":     "30.22035, -92.01707",
            "state":      "Louisiana",
            "pop":        "114214"
        },
        {   "label":      "Provo, Utah",
            "type":       "City",
            "rank":       "212",
            "latlng":     "40.23371, -111.66838",
            "state":      "Utah",
            "pop":        "113984"
        },
        {   "label":      "Visalia, California",
            "type":       "City",
            "rank":       "213",
            "latlng":     "36.33377, -119.29291",
            "state":      "California",
            "pop":        "113487"
        },
        {   "label":      "Ann Arbor, Michigan",
            "type":       "City",
            "rank":       "214",
            "latlng":     "42.28187, -83.74845",
            "state":      "Michigan",
            "pop":        "113206"
        },
        {   "label":      "Clarksville, Tennessee",
            "type":       "City",
            "rank":       "215",
            "latlng":     "36.53075, -87.35977",
            "state":      "Tennessee",
            "pop":        "113175"
        },
        {   "label":      "Peoria, Illinois",
            "type":       "City",
            "rank":       "216",
            "latlng":     "40.69215, -89.58779",
            "state":      "Illinois",
            "pop":        "113107"
        },
        {   "label":      "Cary, North Carolina",
            "type":       "City",
            "rank":       "217",
            "latlng":     "35.78932, -78.78114",
            "state":      "North Carolina",
            "pop":        "112414"
        },
        {   "label":      "Athens-Clarke County (balance), Georgia",
            "type":       "City",
            "rank":       "218",
            "latlng":     "33.957354, -83.376804",
            "state":      "Georgia",
            "pop":        "111580"
        },
        {   "label":      "Beaumont, Texas",
            "type":       "City",
            "rank":       "219",
            "latlng":     "30.08616, -94.10161",
            "state":      "Texas",
            "pop":        "109856"
        },
        {   "label":      "Costa Mesa, California",
            "type":       "City",
            "rank":       "220",
            "latlng":     "33.66383, -117.90344",
            "state":      "California",
            "pop":        "109809"
        },
        {   "label":      "Denton, Texas",
            "type":       "City",
            "rank":       "221",
            "latlng":     "33.2166, -97.13097",
            "state":      "Texas",
            "pop":        "109561"
        },
        {   "label":      "Manchester, New Hampshire",
            "type":       "City",
            "rank":       "222",
            "latlng":     "42.99117, -71.46313",
            "state":      "New Hampshire",
            "pop":        "109497"
        },
        {   "label":      "Independence, Missouri",
            "type":       "City",
            "rank":       "223",
            "latlng":     "39.09324, -94.41567",
            "state":      "Missouri",
            "pop":        "109400"
        },
        {   "label":      "Downey, California",
            "type":       "City",
            "rank":       "224",
            "latlng":     "33.94005, -118.12827",
            "state":      "California",
            "pop":        "109376"
        },
        {   "label":      "Thornton, Colorado",
            "type":       "City",
            "rank":       "225",
            "latlng":     "39.8692, -104.98481",
            "state":      "Colorado",
            "pop":        "109155"
        },
        {   "label":      "Gainesville, Florida",
            "type":       "City",
            "rank":       "226",
            "latlng":     "29.65195, -82.3232",
            "state":      "Florida",
            "pop":        "108655"
        },
        {   "label":      "Santa Clara, California",
            "type":       "City",
            "rank":       "227",
            "latlng":     "37.35545, -121.95427",
            "state":      "California",
            "pop":        "108518"
        },
        {   "label":      "Miramar, Florida",
            "type":       "City",
            "rank":       "228",
            "latlng":     "25.982, -80.22053",
            "state":      "Florida",
            "pop":        "108072"
        },
        {   "label":      "Charleston, South Carolina",
            "type":       "City",
            "rank":       "229",
            "latlng":     "32.78115, -79.9316",
            "state":      "South Carolina",
            "pop":        "107845"
        },
        {   "label":      "West Covina, California",
            "type":       "City",
            "rank":       "230",
            "latlng":     "34.0721, -117.93917",
            "state":      "California",
            "pop":        "107745"
        },
        {   "label":      "Clearwater, Florida",
            "type":       "City",
            "rank":       "231",
            "latlng":     "27.9656, -82.80056",
            "state":      "Florida",
            "pop":        "107742"
        },
        {   "label":      "McKinney, Texas",
            "type":       "City",
            "rank":       "232",
            "latlng":     "33.19894, -96.61496",
            "state":      "Texas",
            "pop":        "107530"
        },
        {   "label":      "Allentown, Pennsylvania",
            "type":       "City",
            "rank":       "233",
            "latlng":     "40.60257, -75.47021",
            "state":      "Pennsylvania",
            "pop":        "107294"
        },
        {   "label":      "Waterbury, Connecticut",
            "type":       "City",
            "rank":       "234",
            "latlng":     "41.55409, -73.04611",
            "state":      "Connecticut",
            "pop":        "107251"
        },
        {   "label":      "Roseville, California",
            "type":       "City",
            "rank":       "235",
            "latlng":     "38.7484, -121.28465",
            "state":      "California",
            "pop":        "107158"
        },
        {   "label":      "Westminster, Colorado",
            "type":       "City",
            "rank":       "236",
            "latlng":     "39.86342, -105.04887",
            "state":      "Colorado",
            "pop":        "105753"
        },
        {   "label":      "Norwalk, California",
            "type":       "City",
            "rank":       "237",
            "latlng":     "33.9156, -118.07248",
            "state":      "California",
            "pop":        "105240"
        },
        {   "label":      "South Bend, Indiana",
            "type":       "City",
            "rank":       "238",
            "latlng":     "41.67905, -86.25403",
            "state":      "Indiana",
            "pop":        "104905"
        },
        {   "label":      "Fairfield, California",
            "type":       "City",
            "rank":       "239",
            "latlng":     "38.24925, -122.04388",
            "state":      "California",
            "pop":        "104897"
        },
        {   "label":      "Arvada, Colorado",
            "type":       "City",
            "rank":       "240",
            "latlng":     "39.80205, -105.08782",
            "state":      "Colorado",
            "pop":        "104830"
        },
        {   "label":      "Pompano Beach, Florida",
            "type":       "City",
            "rank":       "241",
            "latlng":     "26.23106, -80.1596",
            "state":      "Florida",
            "pop":        "104402"
        },
        {   "label":      "Burbank, California",
            "type":       "City",
            "rank":       "242",
            "latlng":     "34.18149, -118.30816",
            "state":      "California",
            "pop":        "104317"
        },
        {   "label":      "San Buenaventura, California",
            "type":       "City",
            "rank":       "243",
            "latlng":     "34.28089, -119.29233",
            "state":      "California",
            "pop":        "104092"
        },
        {   "label":      "Pueblo, Colorado",
            "type":       "City",
            "rank":       "244",
            "latlng":     "38.259, -104.63685",
            "state":      "Colorado",
            "pop":        "103730"
        },
        {   "label":      "Lowell, Massachusetts",
            "type":       "City",
            "rank":       "245",
            "latlng":     "42.64533, -71.31321",
            "state":      "Massachusetts",
            "pop":        "103229"
        },
        {   "label":      "Norman, Oklahoma",
            "type":       "City",
            "rank":       "246",
            "latlng":     "35.22076, -97.44664",
            "state":      "Oklahoma",
            "pop":        "102827"
        },
        {   "label":      "Richmond, California",
            "type":       "City",
            "rank":       "247",
            "latlng":     "37.93776, -122.34271",
            "state":      "California",
            "pop":        "102120"
        },
        {   "label":      "Midland, Texas",
            "type":       "City",
            "rank":       "248",
            "latlng":     "31.99958, -102.07565",
            "state":      "Texas",
            "pop":        "102073"
        },
        {   "label":      "Erie, Pennsylvania",
            "type":       "City",
            "rank":       "249",
            "latlng":     "42.12944, -80.08523",
            "state":      "Pennsylvania",
            "pop":        "102036"
        },
        {   "label":      "Killeen, Texas",
            "type":       "City",
            "rank":       "250",
            "latlng":     "31.11682, -97.72714",
            "state":      "Texas",
            "pop":        "102003"
        },
        {   "label":      "Elgin, Illinois",
            "type":       "City",
            "rank":       "251",
            "latlng":     "42.03962, -88.28323",
            "state":      "Illinois",
            "pop":        "101903"
        },
        {   "label":      "Berkeley, California",
            "type":       "City",
            "rank":       "252",
            "latlng":     "37.8695, -122.27053",
            "state":      "California",
            "pop":        "101555"
        },
        {   "label":      "Portsmouth, Virginia",
            "type":       "City",
            "rank":       "253",
            "latlng":     "36.83264, -76.29772",
            "state":      "Virginia",
            "pop":        "101377"
        },
        {   "label":      "Cambridge, Massachusetts",
            "type":       "City",
            "rank":       "254",
            "latlng":     "42.36683, -71.10599",
            "state":      "Massachusetts",
            "pop":        "101365"
        },
        {   "label":      "Daly City, California",
            "type":       "City",
            "rank":       "255",
            "latlng":     "37.69103, -122.47335",
            "state":      "California",
            "pop":        "101005"
        },
        {   "label":      "Antioch, California",
            "type":       "City",
            "rank":       "256",
            "latlng":     "38.01582, -121.81973",
            "state":      "California",
            "pop":        "100586"
        },
        {   "label":      "Green Bay, Wisconsin",
            "type":       "City",
            "rank":       "257",
            "latlng":     "44.51279, -88.01017",
            "state":      "Wisconsin",
            "pop":        "100353"
        },
        {   "label":      "Billings, Montana",
            "type":       "City",
            "rank":       "258",
            "latlng":     "45.7836, -108.50549",
            "state":      "Montana",
            "pop":        "100148"
        }
    ],
    types: {
        'City': {
            pluralLabel: 'Cities'
        }
    },
    properties: {
        'rank': {
            valueType:              "number"
        },
        'pop': {
            valueType:              "number"
        }
    }
}