#!/usr/bin/env python

# IF YOU ARE SEEING THIS CODE, CHECK THAT CGI EXECUTION IS ENABLED FOR
# THIS SCRIPT IN YOUR WEB SERVER CONFIGURATION

import urllib2
import cgi
import sys, os
import re

# Edit allowed url strings here.  Each string can either be a regular
# expression (beginning with ^), or a string that will be checked
# against the first part of the URL
allowed = [
    'http://localhost',        # allows urls starting with http://localhost
    'http://([^\.]+\.)?example\.com', # allows urls matching regex for *.example.com
    ]

def isAllowed( allowed, url ):
    print >> sys.stderr, allowed, url
    for a in allowed:
        if url.find(a) == 0 or re.match(a,url):
            return True
    return False

method = os.environ["REQUEST_METHOD"]

if method == "POST":
    qs = os.environ["QUERY_STRING"]
    d = cgi.parse_qs(qs)
    if d.has_key("url"):
        url = d["url"][0]
    else:
        url = "http://example.org"
    #AP: the following structure is untested
    for param in d:
        if param != 'url':
                url += '&' + param + '=' + d[param][0]
else:
    fs = cgi.FieldStorage()
    url = fs.getvalue('url', "http://example.org") + '?xz='
    for param in fs:
        if param != 'url':
	    	url += '&' + param + '=' + fs.getvalue(param)

try:
    if not url.startswith("http://") and not url.startswith("https://"):
        url = "http://" + url

    if not isAllowed( allowed, url ):
        print "Status: 403 Forbidden"
        print "Content-Type: text/html\n"
        print "JBrowse proxy not configured to allow this destination."

    elif url.startswith("http://") or url.startswith("https://"):

        if method == "POST":
            length = int(os.environ["CONTENT_LENGTH"])
            headers = {"Content-Type": os.environ["CONTENT_TYPE"]}
            body = sys.stdin.read(length)
            r = urllib2.Request(url, body, headers)
            y = urllib2.urlopen(r)
        else:
            y = urllib2.urlopen(url)

        # print content type header
        i = y.info()
        if i.has_key("Content-Type"):
            print "Content-Type: %s" % (i["Content-Type"])
        else:
            print "Content-Type: text/plain"
        print

        print y.read()

        y.close()
    else:
        print "Content-Type: text/html\n"
        print "Illegal request."

except Exception, E:
    print "Status: 500 Unexpected Error"
    print "Content-Type: text/html\n"
    print "Request failed."
# debug comment out for production
#    print "Some unexpected error occurred. Error text was:", E


