{
    types: {
        "Nobelist" : {
            pluralLabel: "Nobelists"
        }
    },
    properties: {
        "co-winner" : {
            valueType: "item"
        }
    },
    "items" : [
        {   type :                  "Nobelist",
            label :                 "Burton Richter",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Richter",
            "nobel-year" :          "1976",
            relationship :          "alumni",
            "co-winner" :           "Samuel C.C. Ting",
            "relationship-detail" : "MIT S.B. 1952, Ph.D. 1956",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1976/richter_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "George A. Akerlof",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "Akerlof",
            "nobel-year" :          "2001",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1966",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/2001/akerlof_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "William Shockley",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Shockley",
            "nobel-year" :          "1956",
            relationship :          "alumni",
            "deceased" :            "yes",
            "relationship-detail" : "MIT Ph.D. 1936 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1956/shockley_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Daniel C. Tsui",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Tsui",
            "nobel-year" :          "1998",
            relationship :          "research",
            "co-winner" :           [
                "Horst L. St\u00F6rmer",
                "Robert B. Laughlin"
            ],
            "relationship-detail" : "MIT researcher at MIT Magnet Lab",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1998/tsui_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Elias J. Corey Jr.",
            discipline :            "Chemistry",
            shared :                "no",
            "last-name" :           "Corey",
            "nobel-year" :          "1990",
            relationship :          "alumni",
            "relationship-detail" : "MIT S.B. 1948, Ph.D. 1951",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Horst L. St\u00F6rmer",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "St\u00F6rmer",
            "nobel-year" :          "1998",
            relationship :          "research",
            "co-winner" :           [
                "Robert B. Laughlin",
                "Daniel C. Tsui"
            ],
            "relationship-detail" : "MIT researcher at MIT Magnet Lab",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1998/stormer_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Edward M. Purcell",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Purcell",
            "nobel-year" :          "1952",
            relationship :          "research",
            "deceased" :            "yes",
            "relationship-detail" : "Staff, MIT Radiation Laboratory WWII (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1952/purcell_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Phillip A. Sharp",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Sharp",
            "nobel-year" :          "1993",
            relationship :          "professor",
            "relationship-detail" : "MIT Institute Professor, Biology",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/1993/sharp_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Lawrence R. Klein",
            discipline :            "Economics",
            shared :                "no",
            "last-name" :           "Klein",
            "nobel-year" :          "1980",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1944",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1980/klein_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Hans A. Bethe",
            discipline :            "Physics",
            shared :                "no",
            "last-name" :           "Bethe",
            "nobel-year" :          "1967",
            relationship :          "research",
            "relationship-detail" : "MIT Radiation Laboratory WWII",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1967/bethe_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Charles H. Townes",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Townes",
            "nobel-year" :          "1964",
            relationship :          "professor",
            "relationship-detail" : "MIT Provost 1961-61",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1964/townes_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "K. Barry Sharpless",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Sharpless",
            "nobel-year" :          "2001",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Chemistry 1970-77, 1980-90",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/2001/sharpless_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Richard R. Schrock",
            url :                   "http://web.mit.edu/newsoffice/2005/schrock.html",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Schrock",
            "nobel-year" :          "2005",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Chemistry",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/2005/schrock_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Jerome I. Friedman",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Friedman",
            "nobel-year" :          "1990",
            relationship :          "professor",
            "co-winner" :           "Henry W. Kendall",
            "relationship-detail" : "MIT Institute Professor, Physics",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1990/friedman_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Richard P. Feynman",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Feynman",
            "nobel-year" :          "1965",
            relationship :          "alumni",
            "deceased" :            "yes",
            "co-winner" :           "Julian Schwinger",
            "relationship-detail" : "MIT S.B. 1939 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1965/feynman_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "E. Donnall Thomas",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Thomas",
            "nobel-year" :          "1990",
            relationship :          "research",
            "relationship-detail" : "MIT postdoctoral researcher 1950",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/1990/thomas_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Jack Steinberger",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Steinberger",
            "nobel-year" :          "1988",
            relationship :          "research",
            "relationship-detail" : "MIT Radiation Laboratory 1943-45",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1988/steinberger_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Har Gobind Khorana",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Khorana",
            "nobel-year" :          "1968",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Biology and Chemistry",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/1968/khorana_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Joseph E. Stiglitz",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "Stiglitz",
            "nobel-year" :          "2001",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1966",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/2001/stiglitz_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Murray Gell-Mann",
            discipline :            "Physics",
            shared :                "no",
            "last-name" :           "Gell-Mann",
            "nobel-year" :          "1969",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1951",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1969/gell-mann_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "John Forbes Nash, Jr.",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "Nash",
            "nobel-year" :          "1994",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Mathematics 1951-59",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1994/nash_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Salvador E. Luria",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Luria",
            "nobel-year" :          "1969",
            relationship :          "professor",
            "deceased" :            "yes",
            "relationship-detail" : "MIT Professor of Biology (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/1969/luria_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Steven Weinberg",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Weinberg",
            "nobel-year" :          "1979",
            relationship :          "professor",
            "relationship-detail" : "Professor at MIT 1967-73",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1979/weinberg_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Paul A. Samuelson",
            discipline :            "Economics",
            shared :                "no",
            "last-name" :           "Samuelson",
            "nobel-year" :          "1970",
            relationship :          "professor",
            "relationship-detail" : "MIT Institute Professor Emeritus, Economics",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1970/samuelson_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "John Robert Schrieffer",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Schrieffer",
            "nobel-year" :          "1972",
            relationship :          "alumni",
            "relationship-detail" : "MIT S.B. 1953",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1972/schrieffer_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Susumu Tonegawa",
            discipline :            "Medicine/Physiology",
            shared :                "no",
            "last-name" :           "Tonegawa",
            "nobel-year" :          "1987",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Biology",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/1987/tonegawa_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "David Baltimore",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Baltimore",
            "nobel-year" :          "1975",
            relationship :   [
                "research",
                "professor"
            ],
            "relationship-detail" : "MIT postdoctoral researcher, MIT Professor of Biology 1968-90, 1994-97",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/1975/baltimore_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Edwin M. McMillan",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "McMillan",
            "nobel-year" :          "1951",
            relationship :          "research",
            "deceased" :            "yes",
            "relationship-detail" : "Staff, MIT Radiation Laboratory 1940-41 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1951/mcmillan_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Myron S. Scholes",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "Scholes",
            "nobel-year" :          "1997",
            relationship :          "professor",
            "co-winner" :           "Robert C. Merton",
            "relationship-detail" : "MIT Professor of Management 1968-73",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1997/scholes_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Julian Schwinger",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Schwinger",
            "nobel-year" :          "1965",
            relationship :          "research",
            "deceased" :            "yes",
            "co-winner" :           "Richard P. Feynman",
            "relationship-detail" : "MIT Radiation Laboratory WWII (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1965/schwinger_thumb.jpg"
        },
        {   type :                  "Nobelist",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Cornell",
            "nobel-year" :          "2001",
            relationship :          "alumni",
            label :                 "Eric A. Cornell",
            "relationship-detail" : "MIT Ph.D. 1990",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/2001/cornell_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Daniel L. McFadden",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "McFadden",
            "nobel-year" :          "2000",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Economics 1978-91",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/2000/mcfadden_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Wolfgang Ketterle",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Ketterle",
            "nobel-year" :          "2001",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Physics",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/2001/ketterle_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Franco Modigliani",
            discipline :            "Economics",
            shared :                "no",
            "last-name" :           "Modigliani",
            "nobel-year" :          "1985",
            relationship :          "professor",
            "deceased" :            "yes",
            "relationship-detail" : "MIT Institute Professor Emeritus, Management, Economics (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1985/modigliani_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Carl E. Wieman",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Wieman",
            "nobel-year" :          "2001",
            relationship :          "alumni",
            "relationship-detail" : "MIT S.B. 1973",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/2001/wieman_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Charles J. Pedersen",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Pedersen",
            "nobel-year" :          "1987",
            relationship :          "alumni",
            "deceased" :            "yes",
            "relationship-detail" : "MIT S.M. 1927 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1987/pedersen_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Eric S. Chivian",
            discipline :            "Peace",
            shared :                "no",
            "last-name" :           "Chivian",
            "nobel-year" :          "1985",
            relationship :          "staff",
            "relationship-detail" : "Retired MIT psychiatrist, Medical Department",
            imageURL :              "http://people.csail.mit.edu/dfhuynh/projects/nobelists/images/eric-chivian.png",
            imageCredit:            "http://mitworld.mit.edu/video/63/"
        },
        {   type :                  "Nobelist",
            label :                 "Mario J. Molina",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Molina",
            "nobel-year" :          "1995",
            relationship :          "professor",
            "relationship-detail" : "MIT Institute Professor, Earth, Atmospheric and Planetary Sciences/Chemistry, 1989-2004",
            imageURL :              "http://people.csail.mit.edu/dfhuynh/projects/nobelists/images/mario-j-molina.png",
            imageCredit:            "http://mitworld.mit.edu/video/63/"
        },
        {   type :                  "Nobelist",
            label :                 "Robert Burns Woodward",
            discipline :            "Chemistry",
            shared :                "no",
            "last-name" :           "Woodward",
            "nobel-year" :          "1965",
            relationship :          "alumni",
            "deceased" :            "yes",
            "relationship-detail" : "MIT S.B. 1936 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1965/woodward_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Robert B. Laughlin",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Laughlin",
            "nobel-year" :          "1998",
            relationship :          "alumni",
            "co-winner" :           [
                "Horst L. St\u00F6rmer",
                "Daniel C. Tsui"
            ],
            "relationship-detail" : "MIT Ph.D. 1979",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1998/laughlin_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Andrew Fire",
            url :                   "http://web.mit.edu/newsoffice/2006/fire.html",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Fire",
            "nobel-year" :          "2006",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1983",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/2006/fire_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Robert M. Solow",
            discipline :            "Economics",
            shared :                "no",
            "last-name" :           "Solow",
            "nobel-year" :          "1987",
            relationship :          "professor",
            "relationship-detail" : "MIT Institute Professor, Economics",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1987/solow_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Robert S. Mulliken",
            discipline :            "Chemistry",
            shared :                "no",
            "last-name" :           "Mulliken",
            "nobel-year" :          "1966",
            relationship :          "alumni",
            "deceased" :            "yes",
            "relationship-detail" : "MIT S.B. 1917 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1966/mulliken_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Kofi Annan",
            discipline :            "Peace",
            "nobel-year" :          "2001",
            shared :                "yes",
            "relationship-detail" : "MIT S.M. 1972",
            "last-name" :           "Annan",
            imageURL :              "http://nobelprize.org/nobel_prizes/peace/laureates/2001/annan_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Thomas R. Cech",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Cech",
            "nobel-year" :          "1989",
            relationship :          "research",
            "relationship-detail" : "MIT postdoctoral researcher 1975-76",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1989/cech_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Samuel C.C. Ting",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Ting",
            "nobel-year" :          "1976",
            relationship :          "professor",
            "co-winner" :           "Burton Richter",
            "relationship-detail" : "MIT Professor of Physics",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1976/ting_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Isidor Isaac Rabi",
            discipline :            "Physics",
            shared :                "no",
            "last-name" :           "Rabi",
            "nobel-year" :          "1944",
            relationship :          "research",
            "deceased" :            "yes",
            "relationship-detail" : "Associate Director, MIT Radiation Laboratory 1940-45 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1944/rabi_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Luis W. Alvarez",
            discipline :            "Physics",
            shared :                "no",
            "last-name" :           "Alvarez",
            "nobel-year" :          "1968",
            relationship :          "research",
            "deceased" :            "yes",
            "relationship-detail" : "Head, special systems, MIT Radiation Laboratory WWII (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1968/alvarez_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Aaron Ciechanover",
            url :                   "http://nobelprize.org/chemistry/laureates/2004/index.html",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Ciechanover",
            "nobel-year" :          "2004",
            relationship :          "research",
            "relationship-detail" : "MIT postdoctoral researcher 1981-84",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/2004/ciechanover_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Clifford G. Shull",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Shull",
            "nobel-year" :          "1994",
            relationship :          "professor",
            "deceased" :            "yes",
            "relationship-detail" : "MIT Professor Emeritus (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1994/shull_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Norman F. Ramsey",
            discipline :            "Physics",
            shared :                "no",
            "last-name" :           "Ramsey",
            "nobel-year" :          "1989",
            relationship :          "research",
            "relationship-detail" : "Leader, fundamental development group, MIT Radiation Laboratory 1940-42",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1989/ramsey_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Geoffrey Wilkinson",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Wilkinson",
            "nobel-year" :          "1973",
            relationship :          "research",
            "deceased" :            "yes",
            "relationship-detail" : "MIT research associate, 1950 (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1973/wilkinson_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Frank Wilczek",
            url :                   "http://web.mit.edu/newsoffice/2004/nobel-wilczek.html",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Wilczek",
            "nobel-year" :          "2004",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Physics",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/2004/wilczek_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Sidney Altman",
            discipline :            "Chemistry",
            shared :                "yes",
            "last-name" :           "Altman",
            "nobel-year" :          "1989",
            relationship :          "alumni",
            "co-winner" :           "Thomas R. Cech",
            "relationship-detail" : "MIT S.B. 1960",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1989/altman_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Leland H. Hartwell",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Hartwell",
            "nobel-year" :          "2001",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1964",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/2001/hartwell_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Henry W. Kendall",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Kendall",
            "nobel-year" :          "1990",
            relationship :   [
                "alumni",
                "professor"
            ],
            "deceased" :            "yes",
            "co-winner" :           "Jerome I. Friedman",
            "relationship-detail" : "MIT S.B. 1948, Ph.D. 1951, Professor of Physics (deceased)",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1990/kendall_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "George Smoot",
            url :                   "http://web.mit.edu/newsoffice/2006/smoot.html",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Smoot",
            "nobel-year" :          "2006",
            relationship :          "alumni",
            "deceased" :            "no",
            "relationship-detail" : "MIT S.B. 1996",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/2006/smoot_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Robert J. Aumann",
            url :                   "http://nobelprize.org/economics/laureates/2005/press.html",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "Aumann",
            "nobel-year" :          "2005",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1955",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/2005/aumann_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Robert C. Merton",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "Merton",
            "nobel-year" :          "1997",
            relationship :   [
                "alumni",
                "professor"
            ],
            "co-winner" :           "Myron S. Scholes",
            "relationship-detail" : "MIT Professor of Management 1970-88, MIT Ph.D. 1970",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1997/merton_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Robert Engle",
            url :                   "http://nobelprize.org/economics/laureates/2003/index.html",
            discipline :            "Economics",
            shared :                "yes",
            "last-name" :           "Engle",
            "nobel-year" :          "2003",
            relationship :          "professor",
            "relationship-detail" : "MIT Professor of Economics 1969-77",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/2003/engle_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "William D. Phillips",
            discipline :            "Physics",
            shared :                "yes",
            "last-name" :           "Phillips",
            "nobel-year" :          "1997",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1976",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1997/phillips_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "H. Robert Horvitz",
            url :                   "http://web.mit.edu/newsoffice/2002/horvitz-nobel.html",
            discipline :            "Medicine/Physiology",
            shared :                "yes",
            "last-name" :           "Horvitz",
            "nobel-year" :          "2002",
            relationship :   [
                "professor",
                "alumni"
            ],
            "relationship-detail" : "MIT Professor of Biology, MIT S.B. 1968",
            imageURL :              "http://nobelprize.org/nobel_prizes/medicine/laureates/2002/horvitz_thumb.jpg"
        },
        {   type :                  "Nobelist",
            label :                 "Robert A. Mundell",
            discipline :            "Economics",
            shared :                "no",
            "last-name" :           "Mundell",
            "nobel-year" :          "1999",
            relationship :          "alumni",
            "relationship-detail" : "MIT Ph.D. 1956",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/1999/mundell_thumb.jpg"
        }
    ]
}